#!/usr/bin/env python
#
# Create a roostats workspace for LFV analysis
#
# http://root.cern.ch/svn/root/tags/v5-34-00/roofit/histfactory/doc/README
#
# Carlos.Solans@cern.ch
# October 2014

import os
import sys

print "Copy DTD"
os.system("get_histfactory_schema.py config/")

chans=[]

jetbins=["0j"]
l1ptbins=["l1pt0","l1pt1","l1pt2","l1pt3","l1pt4"]


for l1ptbin in l1ptbins:

### DEFINE ME AND EM CHANNELS ###
        print "Generate channel emu %s" % (l1ptbin)
        cmd = "./make_histfactory_channel.py emu_%(bin)s "\
                  "-obs Obs_emu_%(bin)s:data/simple.root:Mcoll_data_EM_%(bin)s_rebin "\
		  "-sig Sig_mue_onEmu_%(bin)s:Mcoll_signal_ME_%(bin)s_rebin "\
		  "-sca MinHalfSig:Sig_mue_onEmu_%(bin)s:-0.5:-0.501:-0.499:True "\
                  "-sys sig_sys:Sig_mue_onEmu_%(bin)s:0.9999:1.0001 "\
		  "-ddb B0_%(bin)s:Base_Bkg_%(bin)s "\
                  "-sca fl1pt_%(bin)s:B0_%(bin)s:1.0:0.01:10.0:False "\
                  "-ssc B0_%(bin)s:B0_%(bin)s "\
		  "-wrsig wrongSig_mue_onEmu_%(bin)s:Mcoll_wrong_signal_ME_%(bin)s_rebin "\
                  "-sca fl1pt_%(bin)s:wrongSig_mue_onEmu_%(bin)s:1.0:0.01:10.0:False "\
		  "-sca halfSig:wrongSig_mue_onEmu_%(bin)s:0.5:0.499:0.501:True "\
                  "config/channel_LFV_emu_%(bin)s.xml" % {'bin' : l1ptbin}
        chans.append("config/channel_LFV_emu_%s.xml" % (l1ptbin))
        print " Executing: %s" % cmd
        os.system(cmd)

#"-sys l1ptsys_%(l1pt)s:B0_%(l1pt)s:%(fl1ptlo).3f:%(fl1pthi).3f "\


	print "Generate channel mue %s" % (l1ptbin)
	cmd = "./make_histfactory_channel.py mue_%(bin)s "\
		  "-obs Obs_mue_%(bin)s:data/simple.root:Mcoll_data_ME_%(bin)s_rebin "\
		  "-sig Sig_mue_%(bin)s:Mcoll_signal_ME_%(bin)s_rebin "\
		  "-sca halfSig:Sig_mue_%(bin)s:0.5:0.499:0.501:True "\
		  "-sys sig_sys:Sig_mue_%(bin)s:0.9999:1.0001 "\
		  "-ddb B0_%(bin)s:Base_Bkg_%(bin)s "\
		  "-ssc B0_%(bin)s:B0_%(bin)s "\
		  "-wrsig wrongSig_mue_%(bin)s:Mcoll_wrong_signal_ME_%(bin)s_rebin "\
		  "-sca MinHalfSig:wrontSig_mue_%(bin)s:-0.5:-0.501:-0.499:True "\
		  "config/channel_LFV_mue_%(bin)s.xml" % {'bin' : l1ptbin}
		
	chans.append("config/channel_LFV_mue_%s.xml" % (l1ptbin))
	print " Executing: %s" % cmd
	os.system(cmd)

### Last l1pt bin with no fpT

print "Generate channel emu l1pt5" 
cmd = "./make_histfactory_channel.py emu_l1pt5 "\
	"-obs Obs_emu_l1pt5:data/simple.root:Mcoll_data_EM_l1pt5_rebin "\
	"-sig Sig_mue_onEmu_l1pt5:Mcoll_signal_ME_l1pt5_rebin "\
	"-sca MinHalfSig:Sig_mue_onEmu_l1pt5:-0.5:-0.501:-0.499:True "\
	"-sys sig_sys:Sig_mue_onEmu_l1pt5:0.9999:1.0001 "\
	"-ddb B0_l1pt5:Base_Bkg_l1pt5 "\
	"-ssc B0_l1pt5:B0_l1pt5 "\
	"-wrsig wrongSig_mue_onEmu_l1pt5:Mcoll_wrong_signal_ME_l1pt5_rebin "\
	"-sca halfSig:wrongSig_mue_onEmu_l1pt5:0.5:0.499:0.501:True "\
        "config/channel_LFV_emu_l1pt5.xml"

chans.append("config/channel_LFV_emu_l1pt5.xml") 
print " Executing: %s" % cmd
os.system(cmd)

print "Generate channel mue l1pt5" 
cmd = "./make_histfactory_channel.py mue_l1pt5 "\
	"-obs Obs_mue_l1pt5:data/simple.root:Mcoll_data_ME_l1pt5_rebin "\
        "-sig Sig_mue_l1pt5:Mcoll_signal_ME_l1pt5_rebin "\
        "-sca halfSig:Sig_mue_l1pt5:0.5:0.499:0.501:True "\
        "-sys sig_sys:Sig_mue_l1pt5:0.9999:1.00001 "\
	"-ddb B0_l1pt5:Base_Bkg_l1pt5 "\
        "-ssc B0_l1pt5:B0_l1pt5 "\
	"-wrsig wrongSig_mue_l1pt5:Mcoll_wrong_signal_ME_l1pt5_rebin "\
	"-sca MinHalfSig:wrontSig_mue_l1pt5:-0.5:-0.501:-0.499:True "\
        "config/channel_LFV_mue_l1pt5.xml" 

chans.append("config/channel_LFV_mue_l1pt5.xml")
print " Executing: %s" % cmd
os.system(cmd)

dic={}
dic["chans"]=' '.join(chans)
print "Generate combination histfactory"
print "**********************************************"

cmd = "./make_histfactory_combination.py -prefix ws_LFV -combinelumi 1 1.034 "\
      "config/combination_LFV.xml "\
      "%(chans)s" % dic
print " Executing: %s" % cmd
os.system(cmd)


cmd = "hist2workspace config/combination_LFV.xml" 
print " Executing: %s" % cmd
os.system(cmd)

    

