#!/usr/bin/env python
#
# Create a roostats workspace for LFV analysis
#
# http://root.cern.ch/svn/root/tags/v5-34-00/roofit/histfactory/doc/README
#
# Carlos.Solans@cern.ch
# October 2014

import os
import sys

print "Copy DTD"
os.system("get_histfactory_schema.py config/")

chans=[]

l1ptbins=["l1pt0","l1pt1","l1pt2","l1pt3","l1pt4","l1pt5"]

emu_EL_RE = {'l1pt0':{'UPvalue':1.002322,'DNvalue':0.995928},
		'l1pt1':{'UPvalue':1.003880,'DNvalue':0.993061},
		'l1pt2':{'UPvalue':1.014695,'DNvalue':0.974285},
		'l1pt3':{'UPvalue':1.016214,'DNvalue':0.971293},
		'l1pt4':{'UPvalue':1.030615,'DNvalue':0.946051},
		'l1pt5':{'UPvalue':1.014868,'DNvalue':0.973419},
		}

emu_EL_FR = {'l1pt0':{'UPvalue':1.009608,'DNvalue':0.987954},
		'l1pt1':{'UPvalue':1.016492,'DNvalue':0.979312},
		'l1pt2':{'UPvalue':1.019051,'DNvalue':0.969388},
		'l1pt3':{'UPvalue':1.021144,'DNvalue':0.965472},
		'l1pt4':{'UPvalue':1.039665,'DNvalue':0.936135},
		'l1pt5':{'UPvalue':1.026588,'DNvalue':0.913753},
		}		

emu_MU_RE = {'l1pt0':{'UPvalue':0.998837,'DNvalue':1.001112},
		'l1pt1':{'UPvalue':0.998419,'DNvalue':1.001509},
		'l1pt2':{'UPvalue':0.999697,'DNvalue':1.000366},
		'l1pt3':{'UPvalue':1.012723,'DNvalue':0.987740},
		'l1pt4':{'UPvalue':1.018250,'DNvalue':0.982556},
		'l1pt5':{'UPvalue':1.005139,'DNvalue':0.995082},
		}		

emu_MU_FR = {'l1pt0':{'UPvalue':1.018467,'DNvalue':0.981791},
		'l1pt1':{'UPvalue':1.017527,'DNvalue':0.982720},
		'l1pt2':{'UPvalue':1.115141,'DNvalue':0.894679},
		'l1pt3':{'UPvalue':1.101712,'DNvalue':0.906168},
		'l1pt4':{'UPvalue':1.097406,'DNvalue':0.909866},
		'l1pt5':{'UPvalue':2.096548,'DNvalue':0.536525},
		}		

mue_EL_RE = {'l1pt0':{'UPvalue':1.012022,'DNvalue':0.985508},
		'l1pt1':{'UPvalue':1.015715,'DNvalue':0.981033},
		'l1pt2':{'UPvalue':1.010617,'DNvalue':0.985354},	
		'l1pt3':{'UPvalue':1.009680,'DNvalue':0.986458},
		'l1pt4':{'UPvalue':1.018714,'DNvalue':0.974089},
		'l1pt5':{'UPvalue':1.016152,'DNvalue':0.971271},
		}		

mue_EL_FR = {'l1pt0':{'UPvalue':1.010489,'DNvalue':0.964592},
		'l1pt1':{'UPvalue':1.013567,'DNvalue':0.955107},
		'l1pt2':{'UPvalue':1.019220,'DNvalue':0.934756},
		'l1pt3':{'UPvalue':1.019358,'DNvalue':0.935352},
		'l1pt4':{'UPvalue':1.034732,'DNvalue':0.882748},
		'l1pt5':{'UPvalue':1.030275,'DNvalue':0.897463},
		}

mue_MU_RE = {'l1pt0':{'UPvalue':1.011649,'DNvalue':0.988401},
		'l1pt1':{'UPvalue':1.009533,'DNvalue':0.990508},
		'l1pt2':{'UPvalue':1.022973,'DNvalue':0.977324},
		'l1pt3':{'UPvalue':1.023721,'DNvalue':0.976626},
		'l1pt4':{'UPvalue':1.024070,'DNvalue':0.976285},
		'l1pt5':{'UPvalue':1.061146,'DNvalue':0.941153},
		}

mue_MU_FR = {'l1pt0':{'UPvalue':1.052617,'DNvalue':0.977827},
		'l1pt1':{'UPvalue':1.277875,'DNvalue':0.882703},
		'l1pt2':{'UPvalue':1.215912,'DNvalue':0.908019},
		'l1pt3':{'UPvalue':1.256100,'DNvalue':0.890794},
		'l1pt4':{'UPvalue':1.246269,'DNvalue':0.898580},
		'l1pt5':{'UPvalue':1.176679,'DNvalue':0.931055},
		}

### SET VALUES FOR FAKE SYSTEMATIC ###
for l1ptbin in l1ptbins:
        cdic = {'l1pt':l1ptbin,
                'emu_DNval_EL_RE':emu_EL_RE[l1ptbin]['DNvalue'],
		'emu_UPval_EL_RE':emu_EL_RE[l1ptbin]['UPvalue'],
		'emu_DNval_EL_FR':emu_EL_FR[l1ptbin]['DNvalue'],
                'emu_UPval_EL_FR':emu_EL_FR[l1ptbin]['UPvalue'],                
		'emu_DNval_MU_RE':emu_MU_RE[l1ptbin]['DNvalue'],
                'emu_UPval_MU_RE':emu_MU_RE[l1ptbin]['UPvalue'],
		'emu_DNval_MU_FR':emu_MU_FR[l1ptbin]['DNvalue'],
                'emu_UPval_MU_FR':emu_MU_FR[l1ptbin]['UPvalue'],
		'mue_DNval_EL_RE':mue_EL_RE[l1ptbin]['DNvalue'],
                'mue_UPval_EL_RE':mue_EL_RE[l1ptbin]['UPvalue'],
                'mue_DNval_EL_FR':mue_EL_FR[l1ptbin]['DNvalue'],
                'mue_UPval_EL_FR':mue_EL_FR[l1ptbin]['UPvalue'], 
                'mue_DNval_MU_RE':mue_MU_RE[l1ptbin]['DNvalue'],
                'mue_UPval_MU_RE':mue_MU_RE[l1ptbin]['UPvalue'],
                'mue_DNval_MU_FR':mue_MU_FR[l1ptbin]['DNvalue'],
                'mue_UPval_MU_FR':mue_MU_FR[l1ptbin]['UPvalue'],
		}


### DEFINE ME AND EM CHANNELS ###
        print "Generate channel emu %s" % (l1ptbin)
        cmd = "./make_histfactory_channel.py emu_%(l1pt)s "\
                  "-obs Obs_emu_%(l1pt)s:data/simple.root:Mcoll_data_EM_%(l1pt)s_rebin "\
                  "-sig Sig_mue_onEmu_%(l1pt)s:Mcoll_signal_ME_%(l1pt)s_rebin "\
		  "-sca MinHalfSig:Sig_mue_onEmu_%(l1pt)s:-0.5:-0.501:-0.499:True "\
		  "-ddb B0_%(l1pt)s:Base_Bkg_%(l1pt)s "\
                  "-sca fl1pt_%(l1pt)s:B0_%(l1pt)s:1.0:0.01:10.0:False "\
                  "-ssc B0_%(l1pt)s:B0_%(l1pt)s "\
		  "-wrsig wrongSig_mue_onEmu_%(l1pt)s:Mcoll_wrong_signal_ME_%(l1pt)s_rebin "\
                  "-sca fl1pt_%(l1pt)s:wrongSig_mue_onEmu_%(l1pt)s:1.0:0.01:10.0:False "\
                  "-sca halfSig:wrongSig_mue_onEmu_%(l1pt)s:0.5:0.499:0.501:True "\
		  "-bkg Fakes_emu_%(l1pt)s:Mcoll_Fakes_EM_%(l1pt)s_rebin "\
		  "-histosys Fakes_EL_RE:Fakes_emu_%(l1pt)s:Mcoll_Fakes_EL_RE_DOWN_EM_%(l1pt)s_rebin:Mcoll_Fakes_EL_RE_UP_EM_%(l1pt)s_rebin "\
                  "-sys Fakes_EL_RE:Fakes_emu_%(l1pt)s:%(emu_DNval_EL_RE).3f:%(emu_UPval_EL_RE).3f "\
                  "-histosys Fakes_EL_FR:Fakes_emu_%(l1pt)s:Mcoll_Fakes_EL_FR_DOWN_EM_%(l1pt)s_rebin:Mcoll_Fakes_EL_FR_UP_EM_%(l1pt)s_rebin "\
                  "-sys Fakes_EL_FR:Fakes_emu_%(l1pt)s:%(emu_DNval_EL_FR).3f:%(emu_UPval_EL_FR).3f "\
                  "-histosys Fakes_MU_RE:Fakes_emu_%(l1pt)s:Mcoll_Fakes_MU_RE_DOWN_EM_%(l1pt)s_rebin:Mcoll_Fakes_MU_RE_UP_EM_%(l1pt)s_rebin "\
                  "-sys Fakes_MU_RE:Fakes_emu_%(l1pt)s:%(emu_DNval_MU_RE).3f:%(emu_UPval_MU_RE).3f "\
                  "-histosys Fakes_MU_FR:Fakes_emu_%(l1pt)s:Mcoll_Fakes_MU_FR_DOWN_EM_%(l1pt)s_rebin:Mcoll_Fakes_MU_FR_UP_EM_%(l1pt)s_rebin "\
                  "-sys Fakes_MU_FR:Fakes_emu_%(l1pt)s:%(emu_DNval_MU_FR).3f:%(emu_UPval_MU_FR).3f "\
		  "config/channel_LFV_emu_%(l1pt)s.xml" % cdic
        chans.append("config/channel_LFV_emu_%s.xml" % (l1ptbin))
        print " Executing: %s" % cmd
        os.system(cmd)


#"-wrsig wrongSig_mue_onEmu_%(l1pt)s:Mcoll_wrong_signal_ME_%(l1pt)s_rebin "\
#                  "-sca fl1pt_%(l1pt)s:wrongSig_mue_onEmu_%(l1pt)s:1.0:0.01:10.0:False "\
#                  "-sca halfSig:wrongSig_mue_onEmu_%(l1pt)s:0.5:0.499:0.501:True "\

#"-bkg Fakes_emu_%(l1pt)s:Mcoll_Fakes_EM_%(l1pt)s_rebin "\
#                  "-histosys Fakes_EL_RE:Fakes_emu_%(l1pt)s:Mcoll_Fakes_EL_RE_DOWN_EM_%(l1pt)s_rebin:Mcoll_Fakes_EL_RE_UP_EM_%(l1pt)s_rebin "\
#                  "-sys Fakes_EL_RE:Fakes_emu_%(l1pt)s:%(emu_DNval_EL_RE).3f:%(emu_UPval_EL_RE).3f "\
#                  "-histosys Fakes_EL_FR:Fakes_emu_%(l1pt)s:Mcoll_Fakes_EL_FR_DOWN_EM_%(l1pt)s_rebin:Mcoll_Fakes_EL_FR_UP_EM_%(l1pt)s_rebin "\
#                  "-sys Fakes_EL_FR:Fakes_emu_%(l1pt)s:%(emu_DNval_EL_FR).3f:%(emu_UPval_EL_FR).3f "\
#                  "-histosys Fakes_MU_RE:Fakes_emu_%(l1pt)s:Mcoll_Fakes_MU_RE_DOWN_EM_%(l1pt)s_rebin:Mcoll_Fakes_MU_RE_UP_EM_%(l1pt)s_rebin "\
#                  "-sys Fakes_MU_RE:Fakes_emu_%(l1pt)s:%(emu_DNval_MU_RE).3f:%(emu_UPval_MU_RE).3f "\
#                  "-histosys Fakes_MU_FR:Fakes_emu_%(l1pt)s:Mcoll_Fakes_MU_FR_DOWN_EM_%(l1pt)s_rebin:Mcoll_Fakes_MU_FR_UP_EM_%(l1pt)s_rebin "\
#                  "-sys Fakes_MU_FR:Fakes_emu_%(l1pt)s:%(emu_DNval_MU_FR).3f:%(emu_UPval_MU_FR).3f "\


	print "Generate channel mue %s" % (l1ptbin)
	cmd = "./make_histfactory_channel.py mue_%(l1pt)s "\
		  "-obs Obs_mue_%(l1pt)s:data/simple.root:Mcoll_data_ME_%(l1pt)s_rebin "\
		  "-sig Sig_mue_%(l1pt)s:Mcoll_signal_ME_%(l1pt)s_rebin "\
		  "-sca halfSig:Sig_mue_%(l1pt)s:0.5:0.499:0.501:True "\
		  "-ddb B0_%(l1pt)s:Base_Bkg_%(l1pt)s "\
		  "-ssc B0_%(l1pt)s:B0_%(l1pt)s "\
		  "-wrsig wrongSig_mue_%(l1pt)s:Mcoll_wrong_signal_ME_%(l1pt)s_rebin "\
                  "-sca MinHalfSig:wrontSig_mue_%(l1pt)s:-0.5:-0.501:-0.499:True "\
		  "-bkg Fakes_mue_%(l1pt)s:Mcoll_Fakes_ME_%(l1pt)s_rebin "\
		  "-histosys Fakes_EL_RE:Fakes_mue_%(l1pt)s:Mcoll_Fakes_EL_RE_DOWN_ME_%(l1pt)s_rebin:Mcoll_Fakes_EL_RE_UP_ME_%(l1pt)s_rebin "\
                  "-sys Fakes_EL_RE:Fakes_mue_%(l1pt)s:%(mue_DNval_EL_RE).3f:%(mue_UPval_EL_RE).3f "\
                  "-histosys Fakes_EL_FR:Fakes_mue_%(l1pt)s:Mcoll_Fakes_EL_FR_DOWN_ME_%(l1pt)s_rebin:Mcoll_Fakes_EL_FR_UP_ME_%(l1pt)s_rebin "\
                  "-sys Fakes_EL_FR:Fakes_mue_%(l1pt)s:%(mue_DNval_EL_FR).3f:%(mue_UPval_EL_FR).3f "\
                  "-histosys Fakes_MU_RE:Fakes_mue_%(l1pt)s:Mcoll_Fakes_MU_RE_DOWN_ME_%(l1pt)s_rebin:Mcoll_Fakes_MU_RE_UP_ME_%(l1pt)s_rebin "\
                  "-sys Fakes_MU_RE:Fakes_mue_%(l1pt)s:%(mue_DNval_MU_RE).3f:%(mue_UPval_MU_RE).3f "\
                  "-histosys Fakes_MU_FR:Fakes_mue_%(l1pt)s:Mcoll_Fakes_MU_FR_DOWN_ME_%(l1pt)s_rebin:Mcoll_Fakes_MU_FR_UP_ME_%(l1pt)s_rebin "\
                  "-sys Fakes_MU_FR:Fakes_mue_%(l1pt)s:%(mue_DNval_MU_FR).3f:%(mue_UPval_MU_FR).3f "\
		  "config/channel_LFV_mue_%(l1pt)s.xml" % cdic
		
	chans.append("config/channel_LFV_mue_%s.xml" % (l1ptbin))
	print " Executing: %s" % cmd
	os.system(cmd)




#"-bkg Fakes_mue_%(l1pt)s:Mcoll_Fakes_ME_%(l1pt)s_rebin "\
#                  "-histosys Fakes_EL_RE:Fakes_mue_%(l1pt)s:Mcoll_Fakes_EL_RE_DOWN_ME_%(l1pt)s_rebin:Mcoll_Fakes_EL_RE_UP_ME_%(l1pt)s_rebin "\
#                  "-sys Fakes_EL_RE:Fakes_mue_%(l1pt)s:%(mue_DNval_EL_RE).3f:%(mue_UPval_EL_RE).3f "\
#                  "-histosys Fakes_EL_FR:Fakes_mue_%(l1pt)s:Mcoll_Fakes_EL_FR_DOWN_ME_%(l1pt)s_rebin:Mcoll_Fakes_EL_FR_UP_ME_%(l1pt)s_rebin "\
#                  "-sys Fakes_EL_FR:Fakes_mue_%(l1pt)s:%(mue_DNval_EL_FR).3f:%(mue_UPval_EL_FR).3f "\
#                  "-histosys Fakes_MU_RE:Fakes_mue_%(l1pt)s:Mcoll_Fakes_MU_RE_DOWN_ME_%(l1pt)s_rebin:Mcoll_Fakes_MU_RE_UP_ME_%(l1pt)s_rebin "\
#                  "-sys Fakes_MU_RE:Fakes_mue_%(l1pt)s:%(mue_DNval_MU_RE).3f:%(mue_UPval_MU_RE).3f "\
#                  "-histosys Fakes_MU_FR:Fakes_mue_%(l1pt)s:Mcoll_Fakes_MU_FR_DOWN_ME_%(l1pt)s_rebin:Mcoll_Fakes_MU_FR_UP_ME_%(l1pt)s_rebin "\
#                  "-sys Fakes_MU_FR:Fakes_mue_%(l1pt)s:%(mue_DNval_MU_FR).3f:%(mue_UPval_MU_FR).3f "\


dic={}
dic["chans"]=' '.join(chans)
print "Generate combination histfactory"
print "**********************************************"

cmd = "./make_histfactory_combination.py -prefix ws_LFV -combinelumi 1 1.034 "\
      "config/combination_LFV.xml "\
      "%(chans)s" % dic
print " Executing: %s" % cmd
os.system(cmd)


cmd = "hist2workspace config/combination_LFV.xml" 
print " Executing: %s" % cmd
os.system(cmd)

    

