#!/usr/bin/env python
#
# Prepare the inputs for HistFactory
#
# Carlos.Solans@cern.ch
# January 2014

import ROOT
import os
import sys
#import AtlasStyle
import array

"""
Prepare a dataset based on the inputs from Suneet (TH2D l1pt vs Mcoll).
"""

#AtlasStyle.SetAtlasStyle()

### INPUT DIR ##################

DIR = "~/HistosApr30/"

### SIGNAL STRENGTH ###########
strength = 0.0

### OUTPUT FILE ##############
fw1 = ROOT.TFile("data/simple.root","RECREATE")
mem = []
tln = ROOT.TLine()
l1b = array.array('d',(12,15,20,25,30,35,1000))
tla = ROOT.TLatex()


#for jet in ('','_jets'):
for jet in ('',):

### FINAL BINNING ############
	### Mcoll Binning for jets sample
	ybinsnew = array.array('f',(0,60,80,100,120,130,140,150,160,180,200,230,260,300,350,400,450))
        ### Mcoll Binning for 0j sample
	if jet=='':
                ybinsnew = array.array('f',(0,60,65,70,75,80,85,90,95,100,105,110,115,120,125,130,135,140,145,150,155,160,165,170,175,180,185,190,195,200,205,210,215,220,225,230,235,240,245,250,260,270,280,290,300,320,350,400,450))
        ### l1pt binning
	xbinsnew = array.array('f',(12,15,20,25,30,35,1000))

#############################

	#### Get EM Files ####

	frEM = ROOT.TFile(DIR+"data_NOM_sr_emu_os%s.root"%jet)

	frEM_fake   = ROOT.TFile(DIR+"fake_NOM_sr_emu_os%s.root"%jet)
	frEM_fake_EL_RE_UP   =   ROOT.TFile(DIR+"fake_EL_RE_UP_sr_emu_os%s.root"%jet)
	frEM_fake_EL_RE_DOWN   = ROOT.TFile(DIR+"fake_EL_RE_DOWN_sr_emu_os%s.root"%jet)
	frEM_fake_EL_FR_UP   =   ROOT.TFile(DIR+"fake_EL_FR_UP_sr_emu_os%s.root"%jet)
	frEM_fake_EL_FR_DOWN   = ROOT.TFile(DIR+"fake_EL_FR_DOWN_sr_emu_os%s.root"%jet)
	frEM_fake_MU_RE_UP   =   ROOT.TFile(DIR+"fake_MU_RE_UP_sr_emu_os%s.root"%jet)
	frEM_fake_MU_RE_DOWN   = ROOT.TFile(DIR+"fake_MU_RE_DOWN_sr_emu_os%s.root"%jet)
	frEM_fake_MU_FR_UP   =   ROOT.TFile(DIR+"fake_MU_FR_UP_sr_emu_os%s.root"%jet)
	frEM_fake_MU_FR_DOWN   = ROOT.TFile(DIR+"fake_MU_FR_DOWN_sr_emu_os%s.root"%jet)

	frME_signaltaue   = ROOT.TFile(DIR+"signaltaue_NOM_sr_mue_os%s.root"%jet)


	### Get EM histograms

	h2emOrig = frEM.Get("h_mcoll_vs_pt1_data_NOM_sr_emu_os%s"%jet).Clone("EM%s"%jet)
	h2emOrig_fake = frEM_fake.Get("h_mcoll_vs_pt1_fake_NOM_sr_emu_os%s"%jet).Clone("EM_fake%s"%jet)
	h2emOrig_fake_EL_RE_UP = frEM_fake_EL_RE_UP.Get("h_mcoll_vs_pt1_fake_EL_RE_UP_sr_emu_os%s"%jet).Clone("EM_fake_EL_RE_UP%s"%jet)
	h2emOrig_fake_EL_RE_DOWN = frEM_fake_EL_RE_DOWN.Get("h_mcoll_vs_pt1_fake_EL_RE_DOWN_sr_emu_os%s"%jet).Clone("EM_fake_EL_RE_DOWN%s"%jet)
	h2emOrig_fake_EL_FR_UP = frEM_fake_EL_FR_UP.Get("h_mcoll_vs_pt1_fake_EL_FR_UP_sr_emu_os%s"%jet).Clone("EM_fake_EL_FR_UP%s"%jet)
	h2emOrig_fake_EL_FR_DOWN = frEM_fake_EL_FR_DOWN.Get("h_mcoll_vs_pt1_fake_EL_FR_DOWN_sr_emu_os%s"%jet).Clone("EM_fake_EL_FR_DOWN%s"%jet)
	h2emOrig_fake_MU_RE_UP = frEM_fake_MU_RE_UP.Get("h_mcoll_vs_pt1_fake_MU_RE_UP_sr_emu_os%s"%jet).Clone("EM_fake_MU_RE_UP%s"%jet)
	h2emOrig_fake_MU_RE_DOWN = frEM_fake_MU_RE_DOWN.Get("h_mcoll_vs_pt1_fake_MU_RE_DOWN_sr_emu_os%s"%jet).Clone("EM_fake_MU_RE_DOWN%s"%jet)
	h2emOrig_fake_MU_FR_UP =   frEM_fake_MU_FR_UP.Get("h_mcoll_vs_pt1_fake_MU_FR_UP_sr_emu_os%s"%jet).Clone("EM_fake_MU_FR_UP%s"%jet)
	h2emOrig_fake_MU_FR_DOWN = frEM_fake_MU_FR_DOWN.Get("h_mcoll_vs_pt1_fake_MU_FR_DOWN_sr_emu_os%s"%jet).Clone("EM_fake_MU_FR_DOWN%s"%jet)
	h2wrsgOrig = frME_signaltaue.Get("h_mcoll_vs_pt1_signaltaue_NOM_sr_mue_os%s"%jet).Clone("ME_signaltaue%s"%jet)


	### Get ME files

	frME = ROOT.TFile(DIR+"data_NOM_sr_mue_os%s.root"%jet)

	frME_fake   = ROOT.TFile(DIR+"fake_NOM_sr_mue_os%s.root"%jet)
	frME_fake_EL_RE_UP   =   ROOT.TFile(DIR+"fake_EL_RE_UP_sr_mue_os%s.root"%jet)
	frME_fake_EL_RE_DOWN   = ROOT.TFile(DIR+"fake_EL_RE_DOWN_sr_mue_os%s.root"%jet)
	frME_fake_EL_FR_UP   =   ROOT.TFile(DIR+"fake_EL_FR_UP_sr_mue_os%s.root"%jet)
	frME_fake_EL_FR_DOWN   = ROOT.TFile(DIR+"fake_EL_FR_DOWN_sr_mue_os%s.root"%jet)
	frME_fake_MU_RE_UP   =   ROOT.TFile(DIR+"fake_MU_RE_UP_sr_mue_os%s.root"%jet)
	frME_fake_MU_RE_DOWN   = ROOT.TFile(DIR+"fake_MU_RE_DOWN_sr_mue_os%s.root"%jet)
	frME_fake_MU_FR_UP   =   ROOT.TFile(DIR+"fake_MU_FR_UP_sr_mue_os%s.root"%jet)
	frME_fake_MU_FR_DOWN   = ROOT.TFile(DIR+"fake_MU_FR_DOWN_sr_mue_os%s.root"%jet)

	frME_signaltaumu   = ROOT.TFile(DIR+"signaltaumu_NOM_sr_mue_os%s.root"%jet)
	#frME_signaltaumu   = ROOT.TFile("~/LFV_Suneet/LFVH_Plots/HistosSys/SR_0j_ME_mcollCorr_x_lept1Pt_189890.root")


	### Get ME histograms
	
	h2meOrig =                 frME.Get("h_mcoll_vs_pt1_data_NOM_sr_mue_os%s"%jet).Clone("ME%s"%jet)
	h2meOrig_fake =            frME_fake.Get("h_mcoll_vs_pt1_fake_NOM_sr_mue_os%s"%jet).Clone("ME_fake%s"%jet)
	h2meOrig_fake_EL_RE_UP =   frME_fake_EL_RE_UP.Get("h_mcoll_vs_pt1_fake_EL_RE_UP_sr_mue_os%s"%jet).Clone("ME_fake_EL_RE_UP%s"%jet)
	h2meOrig_fake_EL_RE_DOWN = frME_fake_EL_RE_DOWN.Get("h_mcoll_vs_pt1_fake_EL_RE_DOWN_sr_mue_os%s"%jet).Clone("ME_fake_EL_RE_DOWN%s"%jet)
	h2meOrig_fake_EL_FR_UP =   frME_fake_EL_FR_UP.Get("h_mcoll_vs_pt1_fake_EL_FR_UP_sr_mue_os%s"%jet).Clone("ME_fake_EL_FR_UP%s"%jet)
	h2meOrig_fake_EL_FR_DOWN = frME_fake_EL_FR_DOWN.Get("h_mcoll_vs_pt1_fake_EL_FR_DOWN_sr_mue_os%s"%jet).Clone("ME_fake_EL_FR_DOWN%s"%jet)
	h2meOrig_fake_MU_RE_UP =   frME_fake_MU_RE_UP.Get("h_mcoll_vs_pt1_fake_MU_RE_UP_sr_mue_os%s"%jet).Clone("ME_fake_MU_RE_UP%s"%jet)
	h2meOrig_fake_MU_RE_DOWN = frME_fake_MU_RE_DOWN.Get("h_mcoll_vs_pt1_fake_MU_RE_DOWN_sr_mue_os%s"%jet).Clone("ME_fake_MU_RE_DOWN%s"%jet)
	h2meOrig_fake_MU_FR_UP =   frME_fake_MU_FR_UP.Get("h_mcoll_vs_pt1_fake_MU_FR_UP_sr_mue_os%s"%jet).Clone("ME_fake_MU_FR_UP%s"%jet)
	h2meOrig_fake_MU_FR_DOWN = frME_fake_MU_FR_DOWN.Get("h_mcoll_vs_pt1_fake_MU_FR_DOWN_sr_mue_os%s"%jet).Clone("ME_fake_MU_FR_DOWN%s"%jet)
	h2sgOrig = frME_signaltaumu.Get("h_mcoll_vs_pt1_signaltaumu_NOM_sr_mue_os%s"%jet).Clone("ME_signaltaumu%s"%jet)
	#h2sgOrig = frME_signaltaumu.Get("h_SR_mcollCorr_x_lept1Pt_189890_CENTRAL").Clone("ME_signaltaumu%s"%jet)
	
	### Signal Systematics
	#h2meOrig_ATLAS_MU_SCALE_DOWN = frME_signaltaumu.Get("h_SR_mcollCorr_x_lept1Pt_189890_MSDOWN").Clone("ME_ATLAS_MU_SCALE_DOWN")
	#h2meOrig_ATLAS_MU_SCALE_UP = frME_signaltaumu.Get("h_SR_mcollCorr_x_lept1Pt_189890_MSUP").Clone("ME_ATLAS_MU_SCALE_UP")	
	#h2meOrig_ATLAS_MET_RESOSOFT_DOWN = frME_signaltaumu.Get("h_SR_mcollCorr_x_lept1Pt_189890_RESOSTDOWN").Clone("ME_ATLAS_MET_RESOSOFT_DOWN")
	#h2meOrig_ATLAS_MET_RESOSOFT_UP = frME_signaltaumu.Get("h_SR_mcollCorr_x_lept1Pt_189890_RESOSTUP").Clone("ME_ATLAS_MET_RESOSOFT_UP")
	

	## Rebin 2D histos ###

	print "Rebinning..."
	xaxis = h2meOrig.GetXaxis()
	yaxis = h2meOrig.GetYaxis()
	
	Sig_xaxis = h2sgOrig.GetXaxis()
	Sig_yaxis = h2sgOrig.GetYaxis()

	### SET TO 1% BR ############################################
	### ONLY IF INPUT IS 100% BR
	#for i in range(Sig_xaxis.GetNbins()):
        #	for j in range(Sig_yaxis.GetNbins()):
        #        	h2sgOrig.SetBinContent(i+1,j+1,h2sgOrig.GetBinContent(i+1,j+1)*0.01)
                	#h2wrsgOrig.SetBinContent(i+1,j+1,h2wrsgOrig.GetBinContent(i+1,j+1)*0.01)
	#		h2sgOrig.SetBinError(i+1,j+1,h2sgOrig.GetBinError(i+1,j+1)*0.01)
			#h2meOrig_ATLAS_MU_SCALE_DOWN.SetBinContent(i+1,j+1,h2meOrig_ATLAS_MU_SCALE_DOWN.GetBinContent(i+1,j+1)*0.01)
			#h2meOrig_ATLAS_MU_SCALE_DOWN.SetBinError(i+1,j+1,h2meOrig_ATLAS_MU_SCALE_DOWN.GetBinError(i+1,j+1)*0.01)
			#h2meOrig_ATLAS_MU_SCALE_UP.SetBinContent(i+1,j+1,h2meOrig_ATLAS_MU_SCALE_UP.GetBinContent(i+1,j+1)*0.01)
			#h2meOrig_ATLAS_MU_SCALE_UP.SetBinError(i+1,j+1,h2meOrig_ATLAS_MU_SCALE_UP.GetBinError(i+1,j+1)*0.01)
	#############################################################


	h2me = ROOT.TH2F("h_SR_ME_Rebinned_mcollCorr_x_pt1_Data%s"%jet, "l_1 p^{T};Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2em = ROOT.TH2F("h_SR_EM_Rebinned_mcollCorr_x_pt1_Data%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2emFakes = ROOT.TH2F("h_SR_EM_Rebinned_mcollCorr_x_pt1_Fakes%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2meFakes = ROOT.TH2F("h_SR_ME_Rebinned_mcollCorr_x_pt1_Fakes%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2emFakes_EL_RE_UP = ROOT.TH2F("h_SR_EM_Rebinned_mcollCorr_x_pt1_Fakes_EL_RE_UP%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2meFakes_EL_RE_UP = ROOT.TH2F("h_SR_ME_Rebinned_mcollCorr_x_pt1_Fakes_EL_RE_UP%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2emFakes_EL_RE_DOWN = ROOT.TH2F("h_SR_EM_Rebinned_mcollCorr_x_pt1_Fakes_EL_RE_DOWN%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2meFakes_EL_RE_DOWN = ROOT.TH2F("h_SR_ME_Rebinned_mcollCorr_x_pt1_Fakes_EL_RE_DOWN%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2emFakes_EL_FR_UP = ROOT.TH2F("h_SR_EM_Rebinned_mcollCorr_x_pt1_Fakes_EL_FR_UP%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2meFakes_EL_FR_UP = ROOT.TH2F("h_SR_ME_Rebinned_mcollCorr_x_pt1_Fakes_EL_FR_UP%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2emFakes_EL_FR_DOWN = ROOT.TH2F("h_SR_EM_Rebinned_mcollCorr_x_pt1_Fakes_EL_FR_DOWN%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2meFakes_EL_FR_DOWN = ROOT.TH2F("h_SR_ME_Rebinned_mcollCorr_x_pt1_Fakes_EL_FR_DOWN%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2emFakes_MU_RE_UP = ROOT.TH2F("h_SR_EM_Rebinned_mcollCorr_x_pt1_Fakes_MU_RE_UP%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2meFakes_MU_RE_UP = ROOT.TH2F("h_SR_ME_Rebinned_mcollCorr_x_pt1_Fakes_MU_RE_UP%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2emFakes_MU_RE_DOWN = ROOT.TH2F("h_SR_EM_Rebinned_mcollCorr_x_pt1_Fakes_MU_RE_DOWN%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2meFakes_MU_RE_DOWN = ROOT.TH2F("h_SR_ME_Rebinned_mcollCorr_x_pt1_Fakes_MU_RE_DOWN%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2emFakes_MU_FR_UP = ROOT.TH2F("h_SR_EM_Rebinned_mcollCorr_x_pt1_Fakes_MU_FR_UP%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2meFakes_MU_FR_UP = ROOT.TH2F("h_SR_ME_Rebinned_mcollCorr_x_pt1_Fakes_MU_FR_UP%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2emFakes_MU_FR_DOWN = ROOT.TH2F("h_SR_EM_Rebinned_mcollCorr_x_pt1_Fakes_MU_FR_DOWN%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2meFakes_MU_FR_DOWN = ROOT.TH2F("h_SR_ME_Rebinned_mcollCorr_x_pt1_Fakes_MU_FR_DOWN%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2sg = ROOT.TH2F("h_SR_Sig_Rebinned_mcollCorr_x_pt1%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	h2wrsg = ROOT.TH2F("h_SR_WrongSig_Rebinned_mcollCorr_x_pt1%s"%jet, ";Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	

	#h2me_ATLAS_MU_SCALE_DOWN = ROOT.TH2F("h_ME_Rebinned_ATLAS_MU_SCALE_DOWN%s"%jet, "l_1 p^{T};Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	#h2me_ATLAS_MU_SCALE_UP = ROOT.TH2F("h_ME_Rebinned_ATLAS_MU_SCALE_UP%s"%jet, "l_1 p^{T};Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)	
	#h2me_ATLAS_MET_RESOSOFT_DOWN = ROOT.TH2F("h_ME_Rebinned_ATLAS_MET_RESOSOFT_DOWN%s"%jet, "l_1 p^{T};Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	#h2me_ATLAS_MET_RESOSOFT_UP = ROOT.TH2F("h_ME_Rebinned_ATLAS_MET_RESOSOFT_UP%s"%jet, "l_1 p^{T};Mcoll (GeV)",len(xbinsnew)-1,xbinsnew,len(ybinsnew)-1,ybinsnew)
	


	for x in range(xaxis.GetNbins()):
		for y in range(yaxis.GetNbins()):
			i=x+1
			j=y+1
			mevalue = h2meOrig.GetBinContent(i,j)
			emvalue = h2emOrig.GetBinContent(i,j)
			emFakesvalue = h2emOrig_fake.GetBinContent(i,j)
			meFakesvalue = h2meOrig_fake.GetBinContent(i,j)
			emFakes_EL_RE_UP = h2emOrig_fake_EL_RE_UP.GetBinContent(i,j)
			meFakes_EL_RE_UP = h2meOrig_fake_EL_RE_UP.GetBinContent(i,j)
			emFakes_EL_RE_DOWN = h2emOrig_fake_EL_RE_DOWN.GetBinContent(i,j)
	                meFakes_EL_RE_DOWN = h2meOrig_fake_EL_RE_DOWN.GetBinContent(i,j)
			emFakes_EL_FR_UP = h2emOrig_fake_EL_FR_UP.GetBinContent(i,j)
	                meFakes_EL_FR_UP = h2meOrig_fake_EL_FR_UP.GetBinContent(i,j)
			emFakes_EL_FR_DOWN = h2emOrig_fake_EL_FR_DOWN.GetBinContent(i,j)
	                meFakes_EL_FR_DOWN = h2meOrig_fake_EL_FR_DOWN.GetBinContent(i,j)
			emFakes_MU_RE_UP = h2emOrig_fake_MU_RE_UP.GetBinContent(i,j)
	                meFakes_MU_RE_UP = h2meOrig_fake_MU_RE_UP.GetBinContent(i,j)
			emFakes_MU_RE_DOWN = h2emOrig_fake_MU_RE_DOWN.GetBinContent(i,j)
	                meFakes_MU_RE_DOWN = h2meOrig_fake_MU_RE_DOWN.GetBinContent(i,j)
			emFakes_MU_FR_UP = h2emOrig_fake_MU_FR_UP.GetBinContent(i,j)
	                meFakes_MU_FR_UP = h2meOrig_fake_MU_FR_UP.GetBinContent(i,j)
			emFakes_MU_FR_DOWN = h2emOrig_fake_MU_FR_DOWN.GetBinContent(i,j)
	                meFakes_MU_FR_DOWN = h2meOrig_fake_MU_FR_DOWN.GetBinContent(i,j)
			#sgvalue = h2sgOrig.GetBinContent(i,j)
			wrsgvalue = h2wrsgOrig.GetBinContent(i,j)
			
			#ATLAS_MU_SCALE_DOWN_value = h2meOrig_ATLAS_MU_SCALE_DOWN.GetBinContent(i,j)
			#ATLAS_MU_SCALE_UP_value = h2meOrig_ATLAS_MU_SCALE_UP.GetBinContent(i,j)
			#ATLAS_MET_RESOSOFT_DOWN_value = h2meOrig_ATLAS_MET_RESOSOFT_DOWN.GetBinContent(i,j)
			#ATLAS_MET_RESOSOFT_UP_value = h2meOrig_ATLAS_MET_RESOSOFT_UP.GetBinContent(i,j)

			
			h2me.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),mevalue)
			h2em.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),emvalue)
			h2emFakes.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),emFakesvalue)
			h2meFakes.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),meFakesvalue)
			h2emFakes_EL_RE_UP.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),emFakes_EL_RE_UP)
	                h2meFakes_EL_RE_UP.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),meFakes_EL_RE_UP)
			h2emFakes_EL_RE_DOWN.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),emFakes_EL_RE_DOWN)
	                h2meFakes_EL_RE_DOWN.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),meFakes_EL_RE_DOWN)
			h2emFakes_EL_FR_UP.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),emFakes_EL_FR_UP)
	                h2meFakes_EL_FR_UP.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),meFakes_EL_FR_UP)
			h2emFakes_EL_FR_DOWN.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),emFakes_EL_FR_DOWN)
	                h2meFakes_EL_FR_DOWN.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),meFakes_EL_FR_DOWN)
			h2emFakes_MU_RE_UP.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),emFakes_MU_RE_UP)
	                h2meFakes_MU_RE_UP.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),meFakes_MU_RE_UP)
			h2emFakes_MU_RE_DOWN.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),emFakes_MU_RE_DOWN)
	                h2meFakes_MU_RE_DOWN.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),meFakes_MU_RE_DOWN)
			h2emFakes_MU_FR_UP.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),emFakes_MU_FR_UP)
	                h2meFakes_MU_FR_UP.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),meFakes_MU_FR_UP)
			h2emFakes_MU_FR_DOWN.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),emFakes_MU_FR_DOWN)
	                h2meFakes_MU_FR_DOWN.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),meFakes_MU_FR_DOWN)
			#h2sg.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),sgvalue)
			h2wrsg.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),wrsgvalue)
			
			#h2me_ATLAS_MU_SCALE_DOWN.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),ATLAS_MU_SCALE_DOWN_value)
			#h2me_ATLAS_MU_SCALE_UP.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),ATLAS_MU_SCALE_UP_value)
			#h2me_ATLAS_MET_RESOSOFT_DOWN.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),ATLAS_MET_RESOSOFT_DOWN_value)
			#h2me_ATLAS_MET_RESOSOFT_UP.Fill(xaxis.GetBinCenter(i),yaxis.GetBinCenter(j),ATLAS_MET_RESOSOFT_UP_value)

	for x in range(Sig_xaxis.GetNbins()):
                for y in range(Sig_yaxis.GetNbins()):	
			i=x+1
                        j=y+1
			sgvalue = h2sgOrig.GetBinContent(i,j)
			#ATLAS_MU_SCALE_DOWN_value = h2meOrig_ATLAS_MU_SCALE_DOWN.GetBinContent(i,j)
                        #ATLAS_MU_SCALE_UP_value = h2meOrig_ATLAS_MU_SCALE_UP.GetBinContent(i,j)
			#ATLAS_MET_RESOSOFT_DOWN_value = h2meOrig_ATLAS_MET_RESOSOFT_DOWN.GetBinContent(i,j)
                        #ATLAS_MET_RESOSOFT_UP_value = h2meOrig_ATLAS_MET_RESOSOFT_UP.GetBinContent(i,j)

			h2sg.Fill(Sig_xaxis.GetBinCenter(i),Sig_yaxis.GetBinCenter(j),sgvalue)
			#h2me_ATLAS_MU_SCALE_DOWN.Fill(Sig_xaxis.GetBinCenter(i),Sig_yaxis.GetBinCenter(j),ATLAS_MU_SCALE_DOWN_value)
                        #h2me_ATLAS_MU_SCALE_UP.Fill(Sig_xaxis.GetBinCenter(i),Sig_yaxis.GetBinCenter(j),ATLAS_MU_SCALE_UP_value)
                        #h2me_ATLAS_MET_RESOSOFT_DOWN.Fill(Sig_xaxis.GetBinCenter(i),Sig_yaxis.GetBinCenter(j),ATLAS_MET_RESOSOFT_DOWN_value)
                        #h2me_ATLAS_MET_RESOSOFT_UP.Fill(Sig_xaxis.GetBinCenter(i),Sig_yaxis.GetBinCenter(j),ATLAS_MET_RESOSOFT_UP_value)


	## Rebin uniformly to indices
	
	nbinsx = h2me.GetXaxis().GetNbins()
	nbinsy = h2me.GetNbinsY()
	
	bpme = array.array('f',(0,)*(nbinsx+1))
	bmme = array.array('f',(0,)*(nbinsy+1))
	
	for j in range(nbinsx+1):
		bpme[j] = h2me.GetXaxis().GetBinLowEdge(j+1)
	for k in range(nbinsy+1):
		bmme[k] = h2me.GetYaxis().GetBinLowEdge(k+1)
	
	
	c3 = ROOT.TCanvas("c3%s"%jet,"Mcol%s"%jet,800,800)
	c3.Divide(3,len(l1b)-1)
	for i in range(len(l1b)-1):
		hme1 = ROOT.TH1F("Mcoll_data_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
		hem1 = ROOT.TH1F("Mcoll_data_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
		hemFakes1 = ROOT.TH1F("Mcoll_Fakes_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
		hmeFakes1 = ROOT.TH1F("Mcoll_Fakes_M_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
		hemFakes_EL_RE_UP1 = ROOT.TH1F("Mcoll_Fakes_EL_RE_UP_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
	        hmeFakes_EL_RE_UP1 = ROOT.TH1F("Mcoll_Fakes_EL_RE_UP_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
		hemFakes_EL_RE_DOWN1 = ROOT.TH1F("Mcoll_Fakes_EL_RE_DOWN_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
	        hmeFakes_EL_RE_DOWN1 = ROOT.TH1F("Mcoll_Fakes_EL_RE_DOWN_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
		hemFakes_EL_FR_UP1 = ROOT.TH1F("Mcoll_Fakes_EL_FR_UP_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
	        hmeFakes_EL_FR_UP1 = ROOT.TH1F("Mcoll_Fakes_EL_FR_UP_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
		hemFakes_EL_FR_DOWN1 = ROOT.TH1F("Mcoll_Fakes_EL_FR_DOWN_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
	        hmeFakes_EL_FR_DOWN1 = ROOT.TH1F("Mcoll_Fakes_EL_FR_DOWN_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
		hemFakes_MU_RE_UP1 = ROOT.TH1F("Mcoll_Fakes_MU_RE_UP_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
	        hmeFakes_MU_RE_UP1 = ROOT.TH1F("Mcoll_Fakes_MU_RE_UP_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
		hemFakes_MU_RE_DOWN1 = ROOT.TH1F("Mcoll_Fakes_MU_RE_DOWN_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
	        hmeFakes_MU_RE_DOWN1 = ROOT.TH1F("Mcoll_Fakes_MU_RE_DOWN_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
		hemFakes_MU_FR_UP1 = ROOT.TH1F("Mcoll_Fakes_MU_FR_UP_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
	        hmeFakes_MU_FR_UP1 = ROOT.TH1F("Mcoll_Fakes_MU_FR_UP_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
		hemFakes_MU_FR_DOWN1 = ROOT.TH1F("Mcoll_Fakes_MU_FR_DOWN_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
	        hmeFakes_MU_FR_DOWN1 = ROOT.TH1F("Mcoll_Fakes_MU_FR_DOWN_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
	
		hsg1 = ROOT.TH1F("Mcoll_signal_ME_l1pt%i%s"%(i,jet),";Mcoll (GeV)",len(bmme)-1,bmme)
		hwrsg1 = ROOT.TH1F("Mcoll_wrong_signal_ME_l1pt%i%s"%(i,jet),";Mcoll (GeV)",len(bmme)-1,bmme)

		#hmeATLAS_MU_SCALE_DOWN1 = ROOT.TH1F("Mcoll_ATLAS_MU_SCALE_DOWN_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
		#hmeATLAS_MU_SCALE_UP1 = ROOT.TH1F("Mcoll_ATLAS_MU_SCALE_UP_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)		
		#hmeATLAS_MET_RESOSOFT_DOWN1 = ROOT.TH1F("Mcoll_ATLAS_MET_RESOSOFT_DOWN_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)
		#hmeATLAS_MET_RESOSOFT_UP1 = ROOT.TH1F("Mcoll_ATLAS_MET_RESOSOFT_UP_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",len(bmme)-1,bmme)

		mem.append(hme1)
		mem.append(hem1)
		mem.append(hsg1)
		mem.append(hwrsg1)
		for pt in bpme:
			htme = ROOT.TH1F("htme","htme",len(bmme)-1,bmme)
			htem = ROOT.TH1F("htem","htem",len(bmme)-1,bmme)
			htemFakes = ROOT.TH1F("htemFakes","htemFakes",len(bmme)-1,bmme)
			htmeFakes = ROOT.TH1F("htmeFakes","htmeFakes",len(bmme)-1,bmme)
			htemFakes_EL_RE_UP = ROOT.TH1F("htemFakes_EL_RE_UP","htemFakes_EL_RE_UP",len(bmme)-1,bmme)
	                htmeFakes_EL_RE_UP = ROOT.TH1F("htmeFakes_EL_RE_UP","htmeFakes_EL_RE_UP",len(bmme)-1,bmme)
			htemFakes_EL_RE_DOWN = ROOT.TH1F("htemFakes_EL_RE_DOWN","htemFakes_EL_RE_DOWN",len(bmme)-1,bmme)
	                htmeFakes_EL_RE_DOWN = ROOT.TH1F("htmeFakes_EL_RE_DOWN","htmeFakes_EL_RE_DOWN",len(bmme)-1,bmme)
			htemFakes_EL_FR_UP = ROOT.TH1F("htemFakes_EL_FR_UP","htemFakes_EL_FR_UP",len(bmme)-1,bmme)
	                htmeFakes_EL_FR_UP = ROOT.TH1F("htmeFakes_EL_FR_UP","htmeFakes_EL_FR_UP",len(bmme)-1,bmme)
			htemFakes_EL_FR_DOWN = ROOT.TH1F("htemFakes_EL_FR_DOWN","htemFakes_EL_FR_DOWN",len(bmme)-1,bmme)
	                htmeFakes_EL_FR_DOWN = ROOT.TH1F("htmeFakes_EL_FR_DOWN","htmeFakes_EL_FR_DOWN",len(bmme)-1,bmme)
			htemFakes_MU_RE_UP = ROOT.TH1F("htemFakes_MU_RE_UP","htemFakes_MU_RE_UP",len(bmme)-1,bmme)
	                htmeFakes_MU_RE_UP = ROOT.TH1F("htmeFakes_MU_RE_UP","htmeFakes_MU_RE_UP",len(bmme)-1,bmme)
			htemFakes_MU_RE_DOWN = ROOT.TH1F("htemFakes_MU_RE_DOWN","htemFakes_MU_RE_DOWN",len(bmme)-1,bmme)
	                htmeFakes_MU_RE_DOWN = ROOT.TH1F("htmeFakes_MU_RE_DOWN","htmeFakes_MU_RE_DOWN",len(bmme)-1,bmme)
			htemFakes_MU_FR_UP = ROOT.TH1F("htemFakes_MU_FR_UP","htemFakes_MU_FR_UP",len(bmme)-1,bmme)
	                htmeFakes_MU_FR_UP = ROOT.TH1F("htmeFakes_MU_FR_UP","htmeFakes_MU_FR_UP",len(bmme)-1,bmme)
			htemFakes_MU_FR_DOWN = ROOT.TH1F("htemFakes_MU_FR_DOWN","htemFakes_MU_FR_DOWN",len(bmme)-1,bmme)
	                htmeFakes_MU_FR_DOWN = ROOT.TH1F("htmeFakes_MU_FR_DOWN","htmeFakes_MU_FR_DOWN",len(bmme)-1,bmme)
			
			#htmeATLAS_MU_SCALE_DOWN = ROOT.TH1F("htmeATLAS_MU_SCALE_DOWN","htmeATLAS_MU_SCALE_DOWN",len(bmme)-1,bmme)
			#htmeATLAS_MU_SCALE_UP = ROOT.TH1F("htmeATLAS_MU_SCALE_UP","htmeATLAS_MU_SCALE_UP",len(bmme)-1,bmme)
			#htmeATLAS_MET_RESOSOFT_DOWN = ROOT.TH1F("htmeATLAS_MET_RESOSOFT_DOWN","htmeATLAS_MET_RESOSOFT_DOWN", len(bmme)-1,bmme)
			#htmeATLAS_MET_RESOSOFT_UP = ROOT.TH1F("htmeATLAS_MET_RESOSOFT_UP","htmeATLAS_MET_RESOSOFT_UP", len(bmme)-1,bmme)


			htsg = ROOT.TH1F("htsg","htsg",len(bmme)-1,bmme)
			htwrsg = ROOT.TH1F("htwrsg","htwrsg",len(bmme)-1,bmme)

			if pt<l1b[i+1] and pt>=l1b[i]:
				if False: print "add pt: %.2f" %pt
				for mass in bmme:
					if False: print "mass:",mass,"pt:",pt,"pt_bin:",l1b[i]
					htme.SetBinContent(htme.FindBin(mass),h2me.GetBinContent(h2me.FindBin(pt,mass)))
					htem.SetBinContent(htem.FindBin(mass),h2em.GetBinContent(h2em.FindBin(pt,mass)))
					htemFakes.SetBinContent(htemFakes.FindBin(mass),h2emFakes.GetBinContent(h2emFakes.FindBin(pt,mass)))
					htmeFakes.SetBinContent(htmeFakes.FindBin(mass),h2meFakes.GetBinContent(h2meFakes.FindBin(pt,mass)))
					htemFakes_EL_RE_UP.SetBinContent(htemFakes_EL_RE_UP.FindBin(mass),h2emFakes_EL_RE_UP.GetBinContent(h2emFakes_EL_RE_UP.FindBin(pt,mass)))
	                                htmeFakes_EL_RE_UP.SetBinContent(htmeFakes_EL_RE_UP.FindBin(mass),h2meFakes_EL_RE_UP.GetBinContent(h2meFakes_EL_RE_UP.FindBin(pt,mass)))
					htemFakes_EL_RE_DOWN.SetBinContent(htemFakes_EL_RE_DOWN.FindBin(mass),h2emFakes_EL_RE_DOWN.GetBinContent(h2emFakes_EL_RE_DOWN.FindBin(pt,mass)))
	                                htmeFakes_EL_RE_DOWN.SetBinContent(htmeFakes_EL_RE_DOWN.FindBin(mass),h2meFakes_EL_RE_DOWN.GetBinContent(h2meFakes_EL_RE_DOWN.FindBin(pt,mass)))
					htemFakes_EL_FR_UP.SetBinContent(htemFakes_EL_FR_UP.FindBin(mass),h2emFakes_EL_FR_UP.GetBinContent(h2emFakes_EL_FR_UP.FindBin(pt,mass)))
	                                htmeFakes_EL_FR_UP.SetBinContent(htmeFakes_EL_FR_UP.FindBin(mass),h2meFakes_EL_FR_UP.GetBinContent(h2meFakes_EL_FR_UP.FindBin(pt,mass)))
					htemFakes_EL_FR_DOWN.SetBinContent(htemFakes_EL_FR_DOWN.FindBin(mass),h2emFakes_EL_FR_DOWN.GetBinContent(h2emFakes_EL_FR_DOWN.FindBin(pt,mass)))
	                                htmeFakes_EL_FR_DOWN.SetBinContent(htmeFakes_EL_FR_DOWN.FindBin(mass),h2meFakes_EL_FR_DOWN.GetBinContent(h2meFakes_EL_FR_DOWN.FindBin(pt,mass)))
					htemFakes_MU_RE_UP.SetBinContent(htemFakes_MU_RE_UP.FindBin(mass),h2emFakes_MU_RE_UP.GetBinContent(h2emFakes_MU_RE_UP.FindBin(pt,mass)))
	                                htmeFakes_MU_RE_UP.SetBinContent(htmeFakes_MU_RE_UP.FindBin(mass),h2meFakes_MU_RE_UP.GetBinContent(h2meFakes_MU_RE_UP.FindBin(pt,mass)))
					htemFakes_MU_RE_DOWN.SetBinContent(htemFakes_MU_RE_DOWN.FindBin(mass),h2emFakes_MU_RE_DOWN.GetBinContent(h2emFakes_MU_RE_DOWN.FindBin(pt,mass)))
	                                htmeFakes_MU_RE_DOWN.SetBinContent(htmeFakes_MU_RE_DOWN.FindBin(mass),h2meFakes_MU_RE_DOWN.GetBinContent(h2meFakes_MU_RE_DOWN.FindBin(pt,mass)))
					htemFakes_MU_FR_UP.SetBinContent(htemFakes_MU_FR_UP.FindBin(mass),h2emFakes_MU_FR_UP.GetBinContent(h2emFakes_MU_FR_UP.FindBin(pt,mass)))
	                                htmeFakes_MU_FR_UP.SetBinContent(htmeFakes_MU_FR_UP.FindBin(mass),h2meFakes_MU_FR_UP.GetBinContent(h2meFakes_MU_FR_UP.FindBin(pt,mass)))
					htemFakes_MU_FR_DOWN.SetBinContent(htemFakes_MU_FR_DOWN.FindBin(mass),h2emFakes_MU_FR_DOWN.GetBinContent(h2emFakes_MU_FR_DOWN.FindBin(pt,mass)))
	                                htmeFakes_MU_FR_DOWN.SetBinContent(htmeFakes_MU_FR_DOWN.FindBin(mass),h2meFakes_MU_FR_DOWN.GetBinContent(h2meFakes_MU_FR_DOWN.FindBin(pt,mass)))
	
					htsg.SetBinContent(htsg.FindBin(mass),h2sg.GetBinContent(h2sg.FindBin(pt,mass)))
					htwrsg.SetBinContent(htwrsg.FindBin(mass),h2wrsg.GetBinContent(h2wrsg.FindBin(pt,mass)))
					
					#htmeATLAS_MU_SCALE_DOWN.SetBinContent(htmeATLAS_MU_SCALE_DOWN.FindBin(mass),h2me_ATLAS_MU_SCALE_DOWN.GetBinContent(h2me_ATLAS_MU_SCALE_DOWN.FindBin(pt,mass)))
					#htmeATLAS_MU_SCALE_UP.SetBinContent(htmeATLAS_MU_SCALE_UP.FindBin(mass),h2me_ATLAS_MU_SCALE_UP.GetBinContent(h2me_ATLAS_MU_SCALE_UP.FindBin(pt,mass)))
					#htmeATLAS_MET_RESOSOFT_DOWN.SetBinContent(htmeATLAS_MET_RESOSOFT_DOWN.FindBin(mass),h2me_ATLAS_MET_RESOSOFT_DOWN.GetBinContent(h2me_ATLAS_MET_RESOSOFT_DOWN.FindBin(pt,mass)))
					#htmeATLAS_MET_RESOSOFT_UP.SetBinContent(htmeATLAS_MET_RESOSOFT_UP.FindBin(mass),h2me_ATLAS_MET_RESOSOFT_UP.GetBinContent(h2me_ATLAS_MET_RESOSOFT_UP.FindBin(pt,mass)))



					htme.SetBinError(htme.FindBin(mass),h2me.GetBinError(h2me.FindBin(pt,mass)))
					htem.SetBinError(htem.FindBin(mass),h2em.GetBinError(h2em.FindBin(pt,mass)))
					htemFakes.SetBinError(htemFakes.FindBin(mass),h2emFakes.GetBinError(h2emFakes.FindBin(pt,mass)))
					htmeFakes.SetBinError(htmeFakes.FindBin(mass),h2meFakes.GetBinError(h2meFakes.FindBin(pt,mass)))
					htemFakes_EL_RE_UP.SetBinError(htemFakes_EL_RE_UP.FindBin(mass),h2emFakes_EL_RE_UP.GetBinError(h2emFakes_EL_RE_UP.FindBin(pt,mass)))
	                                htmeFakes_EL_RE_UP.SetBinError(htmeFakes_EL_RE_UP.FindBin(mass),h2meFakes_EL_RE_UP.GetBinError(h2meFakes_EL_RE_UP.FindBin(pt,mass)))
					htemFakes_EL_RE_DOWN.SetBinError(htemFakes_EL_RE_DOWN.FindBin(mass),h2emFakes_EL_RE_DOWN.GetBinError(h2emFakes_EL_RE_DOWN.FindBin(pt,mass)))
	                                htmeFakes_EL_RE_DOWN.SetBinError(htmeFakes_EL_RE_DOWN.FindBin(mass),h2meFakes_EL_RE_DOWN.GetBinError(h2meFakes_EL_RE_DOWN.FindBin(pt,mass)))
					htemFakes_EL_FR_UP.SetBinError(htemFakes_EL_FR_UP.FindBin(mass),h2emFakes_EL_FR_UP.GetBinError(h2emFakes_EL_FR_UP.FindBin(pt,mass)))
	                                htmeFakes_EL_FR_UP.SetBinError(htmeFakes_EL_FR_UP.FindBin(mass),h2meFakes_EL_FR_UP.GetBinError(h2meFakes_EL_FR_UP.FindBin(pt,mass)))
					htemFakes_EL_FR_DOWN.SetBinError(htemFakes_EL_FR_DOWN.FindBin(mass),h2emFakes_EL_FR_DOWN.GetBinError(h2emFakes_EL_FR_DOWN.FindBin(pt,mass)))
	                                htmeFakes_EL_FR_DOWN.SetBinError(htmeFakes_EL_FR_DOWN.FindBin(mass),h2meFakes_EL_FR_DOWN.GetBinError(h2meFakes_EL_FR_DOWN.FindBin(pt,mass)))
					htemFakes_MU_RE_UP.SetBinError(htemFakes_MU_RE_UP.FindBin(mass),h2emFakes_MU_RE_UP.GetBinError(h2emFakes_MU_RE_UP.FindBin(pt,mass)))
	                                htmeFakes_MU_RE_UP.SetBinError(htmeFakes_MU_RE_UP.FindBin(mass),h2meFakes_MU_RE_UP.GetBinError(h2meFakes_MU_RE_UP.FindBin(pt,mass)))
					htemFakes_MU_RE_DOWN.SetBinError(htemFakes_MU_RE_DOWN.FindBin(mass),h2emFakes_MU_RE_DOWN.GetBinError(h2emFakes_MU_RE_DOWN.FindBin(pt,mass)))
	                                htmeFakes_MU_RE_DOWN.SetBinError(htmeFakes_MU_RE_DOWN.FindBin(mass),h2meFakes_MU_RE_DOWN.GetBinError(h2meFakes_MU_RE_DOWN.FindBin(pt,mass)))
					htemFakes_MU_FR_UP.SetBinError(htemFakes_MU_FR_UP.FindBin(mass),h2emFakes_MU_FR_UP.GetBinError(h2emFakes_MU_FR_UP.FindBin(pt,mass)))
	                                htmeFakes_MU_FR_UP.SetBinError(htmeFakes_MU_FR_UP.FindBin(mass),h2meFakes_MU_FR_UP.GetBinError(h2meFakes_MU_FR_UP.FindBin(pt,mass)))
					htemFakes_MU_FR_DOWN.SetBinError(htemFakes_MU_FR_DOWN.FindBin(mass),h2emFakes_MU_FR_DOWN.GetBinError(h2emFakes_MU_FR_DOWN.FindBin(pt,mass)))
	                                htmeFakes_MU_FR_DOWN.SetBinError(htmeFakes_MU_FR_DOWN.FindBin(mass),h2meFakes_MU_FR_DOWN.GetBinError(h2meFakes_MU_FR_DOWN.FindBin(pt,mass)))
	
					htsg.SetBinError(htsg.FindBin(mass),h2sg.GetBinError(h2sg.FindBin(pt,mass)))
					htwrsg.SetBinError(htwrsg.FindBin(mass),h2wrsg.GetBinError(h2wrsg.FindBin(pt,mass)))


					#htmeATLAS_MU_SCALE_DOWN.SetBinError(htmeATLAS_MU_SCALE_DOWN.FindBin(mass),h2me_ATLAS_MU_SCALE_DOWN.GetBinError(h2me_ATLAS_MU_SCALE_DOWN.FindBin(pt,mass)))
                                        #htmeATLAS_MU_SCALE_UP.SetBinError(htmeATLAS_MU_SCALE_UP.FindBin(mass),h2me_ATLAS_MU_SCALE_UP.GetBinError(h2me_ATLAS_MU_SCALE_UP.FindBin(pt,mass)))
                                        #htmeATLAS_MET_RESOSOFT_DOWN.SetBinError(htmeATLAS_MET_RESOSOFT_DOWN.FindBin(mass),h2me_ATLAS_MET_RESOSOFT_DOWN.GetBinError(h2me_ATLAS_MET_RESOSOFT_DOWN.FindBin(pt,mass)))
                                        #htmeATLAS_MET_RESOSOFT_UP.SetBinError(htmeATLAS_MET_RESOSOFT_UP.FindBin(mass),h2me_ATLAS_MET_RESOSOFT_UP.GetBinError(h2me_ATLAS_MET_RESOSOFT_UP.FindBin(pt,mass)))





				hme1.Add(htme)
				hem1.Add(htem)
				hemFakes1.Add(htemFakes)
				hmeFakes1.Add(htmeFakes)
				hemFakes_EL_RE_UP1.Add(htemFakes_EL_RE_UP)
	                        hmeFakes_EL_RE_UP1.Add(htmeFakes_EL_RE_UP)
				hemFakes_EL_RE_DOWN1.Add(htemFakes_EL_RE_DOWN)
	                        hmeFakes_EL_RE_DOWN1.Add(htmeFakes_EL_RE_DOWN)
				hemFakes_EL_FR_UP1.Add(htemFakes_EL_FR_UP)
	                        hmeFakes_EL_FR_UP1.Add(htmeFakes_EL_FR_UP)
				hemFakes_EL_FR_DOWN1.Add(htemFakes_EL_FR_DOWN)
	                        hmeFakes_EL_FR_DOWN1.Add(htmeFakes_EL_FR_DOWN)
				hemFakes_MU_RE_UP1.Add(htemFakes_MU_RE_UP)
	                        hmeFakes_MU_RE_UP1.Add(htmeFakes_MU_RE_UP)
				hemFakes_MU_RE_DOWN1.Add(htemFakes_MU_RE_DOWN)
	                        hmeFakes_MU_RE_DOWN1.Add(htmeFakes_MU_RE_DOWN)
				hemFakes_MU_FR_UP1.Add(htemFakes_MU_FR_UP)
	                        hmeFakes_MU_FR_UP1.Add(htmeFakes_MU_FR_UP)
				hemFakes_MU_FR_DOWN1.Add(htemFakes_MU_FR_DOWN)
	                        hmeFakes_MU_FR_DOWN1.Add(htmeFakes_MU_FR_DOWN)
				hsg1.Add(htsg)
				hwrsg1.Add(htwrsg)
				#hmeATLAS_MU_SCALE_DOWN1.Add(htmeATLAS_MU_SCALE_DOWN)
				#hmeATLAS_MU_SCALE_UP1.Add(htmeATLAS_MU_SCALE_UP)
				#hmeATLAS_MET_RESOSOFT_DOWN1.Add(htmeATLAS_MET_RESOSOFT_DOWN)
				#hmeATLAS_MET_RESOSOFT_UP1.Add(htmeATLAS_MET_RESOSOFT_UP)
			
			htme.Clear()
			htem.Clear()
			htemFakes.Clear()
			htmeFakes.Clear()
			htemFakes_EL_RE_UP.Clear()
	                htmeFakes_EL_RE_UP.Clear()
			htemFakes_EL_RE_DOWN.Clear()
	                htmeFakes_EL_RE_DOWN.Clear()
			htemFakes_EL_FR_UP.Clear()
	                htmeFakes_EL_FR_UP.Clear()
			htemFakes_EL_FR_DOWN.Clear()
	                htmeFakes_EL_FR_DOWN.Clear()
			htemFakes_MU_RE_UP.Clear()
	                htmeFakes_MU_RE_UP.Clear()
			htemFakes_MU_RE_DOWN.Clear()
	                htmeFakes_MU_RE_DOWN.Clear()
			htemFakes_MU_FR_UP.Clear()
	                htmeFakes_MU_FR_UP.Clear()
			htemFakes_MU_FR_DOWN.Clear()
	                htmeFakes_MU_FR_DOWN.Clear()
			htsg.Clear()
			htwrsg.Clear()
			#htmeATLAS_MU_SCALE_DOWN.Clear()
			#htmeATLAS_MU_SCALE_UP.Clear()
			#htmeATLAS_MET_RESOSOFT_DOWN.Clear()
			#htmeATLAS_MET_RESOSOFT_UP.Clear()

		
		#### ADD SIGNAL TO SUM MC ###
		hme1.Add(hsg1,strength)
		hem1.Add(hwrsg1,strength)
		####
	
		c3.cd(3*i+1)
		hme1.Draw()
		#tla.DrawLatexNDC(0.3,0.8,"Mcoll data ME %s l1pt %i-%i"%(jet,l1b[i],l1b[i+1]))
		c3.cd(3*i+2)
		hem1.Draw()
		#tla.DrawLatexNDC(0.3,0.8,"Mcoll data EM %s l1pt %i-%i"%(jet,l1b[i],l1b[i+1]))
		c3.cd(3*i+3)
		hsg1.Draw()
		#tla.DrawLatexNDC(0.3,0.8,"Mcoll signal ME %s l1pt %i-%i"%(jet,l1b[i],l1b[i+1]))
		fw1.cd()
		hme1.Write()
		hem1.Write()
		hsg1.Write()
		hwrsg1.Write()
		if False: print "Rebin histos"
		##throw away first bins
		nthrow = 0
		hme2 = ROOT.TH1F("Mcoll_data_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		hem2 = ROOT.TH1F("Mcoll_data_EM_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		hemFakes2 = ROOT.TH1F("Mcoll_Fakes_EM_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		hmeFakes2 = ROOT.TH1F("Mcoll_Fakes_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		hemFakes_EL_RE_UP2 = ROOT.TH1F("Mcoll_Fakes_EL_RE_UP_EM_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
	        hmeFakes_EL_RE_UP2 = ROOT.TH1F("Mcoll_Fakes_EL_RE_UP_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		hemFakes_EL_RE_DOWN2 = ROOT.TH1F("Mcoll_Fakes_EL_RE_DOWN_EM_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
	        hmeFakes_EL_RE_DOWN2 = ROOT.TH1F("Mcoll_Fakes_EL_RE_DOWN_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		hemFakes_EL_FR_UP2 = ROOT.TH1F("Mcoll_Fakes_EL_FR_UP_EM_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
	        hmeFakes_EL_FR_UP2 = ROOT.TH1F("Mcoll_Fakes_EL_FR_UP_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		hemFakes_EL_FR_DOWN2 = ROOT.TH1F("Mcoll_Fakes_EL_FR_DOWN_EM_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
	        hmeFakes_EL_FR_DOWN2 = ROOT.TH1F("Mcoll_Fakes_EL_FR_DOWN_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		hemFakes_MU_RE_UP2 = ROOT.TH1F("Mcoll_Fakes_MU_RE_UP_EM_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
	        hmeFakes_MU_RE_UP2 = ROOT.TH1F("Mcoll_Fakes_MU_RE_UP_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		hemFakes_MU_RE_DOWN2 = ROOT.TH1F("Mcoll_Fakes_MU_RE_DOWN_EM_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
	        hmeFakes_MU_RE_DOWN2 = ROOT.TH1F("Mcoll_Fakes_MU_RE_DOWN_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		hemFakes_MU_FR_UP2 = ROOT.TH1F("Mcoll_Fakes_MU_FR_UP_EM_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
	        hmeFakes_MU_FR_UP2 = ROOT.TH1F("Mcoll_Fakes_MU_FR_UP_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		hemFakes_MU_FR_DOWN2 = ROOT.TH1F("Mcoll_Fakes_MU_FR_DOWN_EM_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
	        hmeFakes_MU_FR_DOWN2 = ROOT.TH1F("Mcoll_Fakes_MU_FR_DOWN_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		hsg2 = ROOT.TH1F("Mcoll_signal_ME_l1pt%i%s_rebin"%(i,jet),";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		hwrsg2 = ROOT.TH1F("Mcoll_wrong_signal_ME_l1pt%i%s_rebin"%(i,jet),";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)

		#hmeATLAS_MU_SCALE_DOWN2 = ROOT.TH1F("Mcoll_ATLAS_MU_SCALE_DOWN_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		#hmeATLAS_MU_SCALE_UP2 = ROOT.TH1F("Mcoll_ATLAS_MU_SCALE_UP_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		#hmeATLAS_MET_RESOSOFT_DOWN2 = ROOT.TH1F("Mcoll_ATLAS_MET_RESOSOFT_DOWN_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)
		#hmeATLAS_MET_RESOSOFT_UP2 = ROOT.TH1F("Mcoll_ATLAS_MET_RESOSOFT_UP_ME_l1pt%i%s_rebin"%(i,jet),  ";Mcoll (index)",len(bmme)-nthrow,0,len(bmme)-nthrow)


		mem.append(hme2)
		mem.append(hem2)
		mem.append(hemFakes2)
		mem.append(hmeFakes2)
		mem.append(hsg2)
		mem.append(hwrsg2)
		
		for b in range(len(bmme)-nthrow):
			if hme1.GetBinContent(b+1+nthrow)>0:
				hme2.SetBinContent(b+1,hme1.GetBinContent(b+1+nthrow))
				hme2.SetBinError(b+1,hme1.GetBinError(b+1+nthrow))
			else:
				hme2.SetBinContent(b+1,0.001)
				hme2.SetBinError(b+1,0.00001)
			if hem1.GetBinContent(b+1+nthrow)>0:
				hem2.SetBinContent(b+1,hem1.GetBinContent(b+1+nthrow))
				hem2.SetBinError(b+1,hem1.GetBinError(b+1+nthrow))
			else:
				hem2.SetBinContent(b+1,0.001)
				hem2.SetBinError(b+1,0.00001)
			if hemFakes1.GetBinContent(b+1+nthrow)>0:
	                        hemFakes2.SetBinContent(b+1,hemFakes1.GetBinContent(b+1+nthrow))
	                        hemFakes2.SetBinError(b+1,hemFakes1.GetBinError(b+1+nthrow))
	                else:
	                        hemFakes2.SetBinContent(b+1,0.001)
	                        hemFakes2.SetBinError(b+1,0.00001)
			if hmeFakes1.GetBinContent(b+1+nthrow)>0:
	                        hmeFakes2.SetBinContent(b+1,hmeFakes1.GetBinContent(b+1+nthrow))
	                        hmeFakes2.SetBinError(b+1,hmeFakes1.GetBinError(b+1+nthrow))
	                else:
	                        hmeFakes2.SetBinContent(b+1,0.001)
	                        hmeFakes2.SetBinError(b+1,0.00001)
			if hemFakes_EL_RE_UP1.GetBinContent(b+1+nthrow)>0:
	                        hemFakes_EL_RE_UP2.SetBinContent(b+1,hemFakes_EL_RE_UP1.GetBinContent(b+1+nthrow))
	                        hemFakes_EL_RE_UP2.SetBinError(b+1,hemFakes_EL_RE_UP1.GetBinError(b+1+nthrow))
	                else:
	                        hemFakes_EL_RE_UP2.SetBinContent(b+1,0.001)
	                        hemFakes_EL_RE_UP2.SetBinError(b+1,0.00001)
	                if hmeFakes_EL_RE_UP1.GetBinContent(b+1+nthrow)>0:
	                        hmeFakes_EL_RE_UP2.SetBinContent(b+1,hmeFakes_EL_RE_UP1.GetBinContent(b+1+nthrow))
	                        hmeFakes_EL_RE_UP2.SetBinError(b+1,hmeFakes_EL_RE_UP1.GetBinError(b+1+nthrow))
	                else:
	                        hmeFakes_EL_RE_UP2.SetBinContent(b+1,0.001)
	                        hmeFakes_EL_RE_UP2.SetBinError(b+1,0.00001)
			if hemFakes_EL_RE_DOWN1.GetBinContent(b+1+nthrow)>0:
	                        hemFakes_EL_RE_DOWN2.SetBinContent(b+1,hemFakes_EL_RE_DOWN1.GetBinContent(b+1+nthrow))
	                        hemFakes_EL_RE_DOWN2.SetBinError(b+1,hemFakes_EL_RE_DOWN1.GetBinError(b+1+nthrow))
	                else:
	                        hemFakes_EL_RE_DOWN2.SetBinContent(b+1,0.001)
	                        hemFakes_EL_RE_DOWN2.SetBinError(b+1,0.00001)
	                if hmeFakes_EL_RE_DOWN1.GetBinContent(b+1+nthrow)>0:
	                        hmeFakes_EL_RE_DOWN2.SetBinContent(b+1,hmeFakes_EL_RE_DOWN1.GetBinContent(b+1+nthrow))
	                        hmeFakes_EL_RE_DOWN2.SetBinError(b+1,hmeFakes_EL_RE_DOWN1.GetBinError(b+1+nthrow))
	                else:
	                        hmeFakes_EL_RE_DOWN2.SetBinContent(b+1,0.001)
	                        hmeFakes_EL_RE_DOWN2.SetBinError(b+1,0.00001)
			if hemFakes_EL_FR_UP1.GetBinContent(b+1+nthrow)>0:
	                        hemFakes_EL_FR_UP2.SetBinContent(b+1,hemFakes_EL_FR_UP1.GetBinContent(b+1+nthrow))
	                        hemFakes_EL_FR_UP2.SetBinError(b+1,hemFakes_EL_FR_UP1.GetBinError(b+1+nthrow))
	                else:
	                        hemFakes_EL_FR_UP2.SetBinContent(b+1,0.001)
	                        hemFakes_EL_FR_UP2.SetBinError(b+1,0.00001)
	                if hmeFakes_EL_FR_UP1.GetBinContent(b+1+nthrow)>0:
	                        hmeFakes_EL_FR_UP2.SetBinContent(b+1,hmeFakes_EL_FR_UP1.GetBinContent(b+1+nthrow))
	                        hmeFakes_EL_FR_UP2.SetBinError(b+1,hmeFakes_EL_FR_UP1.GetBinError(b+1+nthrow))
	                else:
	                        hmeFakes_EL_FR_UP2.SetBinContent(b+1,0.001)
	                        hmeFakes_EL_FR_UP2.SetBinError(b+1,0.00001)
			if hemFakes_EL_FR_DOWN1.GetBinContent(b+1+nthrow)>0:
	                        hemFakes_EL_FR_DOWN2.SetBinContent(b+1,hemFakes_EL_FR_DOWN1.GetBinContent(b+1+nthrow))
	                        hemFakes_EL_FR_DOWN2.SetBinError(b+1,hemFakes_EL_FR_DOWN1.GetBinError(b+1+nthrow))
	                else:
	                        hemFakes_EL_FR_DOWN2.SetBinContent(b+1,0.001)
	                        hemFakes_EL_FR_DOWN2.SetBinError(b+1,0.00001)
	                if hmeFakes_EL_FR_DOWN1.GetBinContent(b+1+nthrow)>0:
	                        hmeFakes_EL_FR_DOWN2.SetBinContent(b+1,hmeFakes_EL_FR_DOWN1.GetBinContent(b+1+nthrow))
	                        hmeFakes_EL_FR_DOWN2.SetBinError(b+1,hmeFakes_EL_FR_DOWN1.GetBinError(b+1+nthrow))
	                else:
	                        hmeFakes_EL_FR_DOWN2.SetBinContent(b+1,0.001)
	                        hmeFakes_EL_FR_DOWN2.SetBinError(b+1,0.00001)
			if hemFakes_MU_RE_UP1.GetBinContent(b+1+nthrow)>0:
	                        hemFakes_MU_RE_UP2.SetBinContent(b+1,hemFakes_MU_RE_UP1.GetBinContent(b+1+nthrow))
	                        hemFakes_MU_RE_UP2.SetBinError(b+1,hemFakes_MU_RE_UP1.GetBinError(b+1+nthrow))
	                else:
	                        hemFakes_MU_RE_UP2.SetBinContent(b+1,0.001)
	                        hemFakes_MU_RE_UP2.SetBinError(b+1,0.00001)
	                if hmeFakes_MU_RE_UP1.GetBinContent(b+1+nthrow)>0:
	                        hmeFakes_MU_RE_UP2.SetBinContent(b+1,hmeFakes_MU_RE_UP1.GetBinContent(b+1+nthrow))
	                        hmeFakes_MU_RE_UP2.SetBinError(b+1,hmeFakes_MU_RE_UP1.GetBinError(b+1+nthrow))
	                else:
	                        hmeFakes_MU_RE_UP2.SetBinContent(b+1,0.001)
	                        hmeFakes_MU_RE_UP2.SetBinError(b+1,0.00001)
			if hemFakes_MU_RE_DOWN1.GetBinContent(b+1+nthrow)>0:
	                        hemFakes_MU_RE_DOWN2.SetBinContent(b+1,hemFakes_MU_RE_DOWN1.GetBinContent(b+1+nthrow))
	                        hemFakes_MU_RE_DOWN2.SetBinError(b+1,hemFakes_MU_RE_DOWN1.GetBinError(b+1+nthrow))
	                else:
	                        hemFakes_MU_RE_DOWN2.SetBinContent(b+1,0.001)
	                        hemFakes_MU_RE_DOWN2.SetBinError(b+1,0.00001)
	                if hmeFakes_MU_RE_DOWN1.GetBinContent(b+1+nthrow)>0:
	                        hmeFakes_MU_RE_DOWN2.SetBinContent(b+1,hmeFakes_MU_RE_DOWN1.GetBinContent(b+1+nthrow))
	                        hmeFakes_MU_RE_DOWN2.SetBinError(b+1,hmeFakes_MU_RE_DOWN1.GetBinError(b+1+nthrow))
	                else:
	                        hmeFakes_MU_RE_DOWN2.SetBinContent(b+1,0.001)
	                        hmeFakes_MU_RE_DOWN2.SetBinError(b+1,0.00001)
			if hemFakes_MU_FR_UP1.GetBinContent(b+1+nthrow)>0:
	                        hemFakes_MU_FR_UP2.SetBinContent(b+1,hemFakes_MU_FR_UP1.GetBinContent(b+1+nthrow))
	                        hemFakes_MU_FR_UP2.SetBinError(b+1,hemFakes_MU_FR_UP1.GetBinError(b+1+nthrow))
	                else:
	                        hemFakes_MU_FR_UP2.SetBinContent(b+1,0.001)
	                        hemFakes_MU_FR_UP2.SetBinError(b+1,0.00001)
	                if hmeFakes_MU_FR_UP1.GetBinContent(b+1+nthrow)>0:
	                        hmeFakes_MU_FR_UP2.SetBinContent(b+1,hmeFakes_MU_FR_UP1.GetBinContent(b+1+nthrow))
	                        hmeFakes_MU_FR_UP2.SetBinError(b+1,hmeFakes_MU_FR_UP1.GetBinError(b+1+nthrow))
	                else:
	                        hmeFakes_MU_FR_UP2.SetBinContent(b+1,0.001)
	                        hmeFakes_MU_FR_UP2.SetBinError(b+1,0.00001)
			if hemFakes_MU_FR_DOWN1.GetBinContent(b+1+nthrow)>0:
	                        hemFakes_MU_FR_DOWN2.SetBinContent(b+1,hemFakes_MU_FR_DOWN1.GetBinContent(b+1+nthrow))
	                        hemFakes_MU_FR_DOWN2.SetBinError(b+1,hemFakes_MU_FR_DOWN1.GetBinError(b+1+nthrow))
	                else:
	                        hemFakes_MU_FR_DOWN2.SetBinContent(b+1,0.001)
	                        hemFakes_MU_FR_DOWN2.SetBinError(b+1,0.00001)
	                if hmeFakes_MU_FR_DOWN1.GetBinContent(b+1+nthrow)>0:
	                        hmeFakes_MU_FR_DOWN2.SetBinContent(b+1,hmeFakes_MU_FR_DOWN1.GetBinContent(b+1+nthrow))
	                        hmeFakes_MU_FR_DOWN2.SetBinError(b+1,hmeFakes_MU_FR_DOWN1.GetBinError(b+1+nthrow))
	                else:
	                        hmeFakes_MU_FR_DOWN2.SetBinContent(b+1,0.001)
	                        hmeFakes_MU_FR_DOWN2.SetBinError(b+1,0.00001)
			if hsg1.GetBinContent(b+1+nthrow)>0:
				hsg2.SetBinContent(b+1,hsg1.GetBinContent(b+1+nthrow))
				hsg2.SetBinError(b+1,hsg1.GetBinError(b+1+nthrow))
			else:
				hsg2.SetBinContent(b+1,0.001)
				hsg2.SetBinError(b+1,0.00001)
			if hwrsg1.GetBinContent(b+1+nthrow)>0:
	                        hwrsg2.SetBinContent(b+1,hwrsg1.GetBinContent(b+1+nthrow))
	                        hwrsg2.SetBinError(b+1,hwrsg1.GetBinError(b+1+nthrow))
	                else:
	                        hwrsg2.SetBinContent(b+1,0.001)
	                        hwrsg2.SetBinError(b+1,0.00001)
			if hwrsg2.GetBinContent(b+1)<0:
				print "NEGATIVE VALUES in wrong signal sample!"


			#if hmeATLAS_MU_SCALE_DOWN1.GetBinContent(b+1+nthrow)>0:
			#	hmeATLAS_MU_SCALE_DOWN2.SetBinContent(b+1,hmeATLAS_MU_SCALE_DOWN1.GetBinContent(b+1+nthrow))
			#	hmeATLAS_MU_SCALE_DOWN2.SetBinError(b+1,hmeATLAS_MU_SCALE_DOWN1.GetBinError(b+1+nthrow))
			#else:
			#	hmeATLAS_MU_SCALE_DOWN2.SetBinContent(b+1,0.001)
			#	hmeATLAS_MU_SCALE_DOWN2.SetBinError(b+1,0.00001)
			#if hmeATLAS_MU_SCALE_UP1.GetBinContent(b+1+nthrow)>0:
			#	hmeATLAS_MU_SCALE_UP2.SetBinContent(b+1,hmeATLAS_MU_SCALE_UP1.GetBinContent(b+1+nthrow))
			#	hmeATLAS_MU_SCALE_UP2.SetBinError(b+1,hmeATLAS_MU_SCALE_UP1.GetBinError(b+1+nthrow))
			#else:
			#	hmeATLAS_MU_SCALE_UP2.SetBinContent(b+1,0.001)
			#	hmeATLAS_MU_SCALE_UP2.SetBinError(b+1,0.00001)
			#if hmeATLAS_MET_RESOSOFT_DOWN1.GetBinContent(b+1+nthrow)>0:
			#	hmeATLAS_MET_RESOSOFT_DOWN2.SetBinContent(b+1,hmeATLAS_MET_RESOSOFT_DOWN1.GetBinContent(b+1+nthrow))
			#	hmeATLAS_MET_RESOSOFT_DOWN2.SetBinError(b+1,hmeATLAS_MET_RESOSOFT_DOWN1.GetBinError(b+1+nthrow))
			#else:
			#	hmeATLAS_MET_RESOSOFT_DOWN2.SetBinContent(b+1,0.001)
			#	hmeATLAS_MET_RESOSOFT_DOWN2.SetBinError(b+1,0.00001)
			#if hmeATLAS_MET_RESOSOFT_UP1.GetBinContent(b+1+nthrow)>0:
                        #	hmeATLAS_MET_RESOSOFT_UP2.SetBinContent(b+1,hmeATLAS_MET_RESOSOFT_UP1.GetBinContent(b+1+nthrow))
                         #       hmeATLAS_MET_RESOSOFT_UP2.SetBinError(b+1,hmeATLAS_MET_RESOSOFT_UP1.GetBinError(b+1+nthrow))
                        #else:
                        #        hmeATLAS_MET_RESOSOFT_UP2.SetBinContent(b+1,0.001)
                        #        hmeATLAS_MET_RESOSOFT_UP2.SetBinError(b+1,0.00001)

								


		### Get scaling for fake systematics 
		nomFakes_emu = hemFakes2.Integral()
		DNFakes_emu_EL_RE = hemFakes_EL_RE_DOWN2.Integral()
		UPFakes_emu_EL_RE = hemFakes_EL_RE_UP2.Integral()
		DNFakes_emu_EL_FR = hemFakes_EL_FR_DOWN2.Integral()
	        UPFakes_emu_EL_FR = hemFakes_EL_FR_UP2.Integral()
		DNFakes_emu_MU_RE = hemFakes_MU_RE_DOWN2.Integral()
	        UPFakes_emu_MU_RE = hemFakes_MU_RE_UP2.Integral()
		DNFakes_emu_MU_FR = hemFakes_MU_FR_DOWN2.Integral()
	        UPFakes_emu_MU_FR = hemFakes_MU_FR_UP2.Integral()
		nomFakes_mue = hmeFakes2.Integral()
	        DNFakes_mue_EL_RE = hmeFakes_EL_RE_DOWN2.Integral()
	        UPFakes_mue_EL_RE = hmeFakes_EL_RE_UP2.Integral()
	        DNFakes_mue_EL_FR = hmeFakes_EL_FR_DOWN2.Integral()
	        UPFakes_mue_EL_FR = hmeFakes_EL_FR_UP2.Integral()
	        DNFakes_mue_MU_RE = hmeFakes_MU_RE_DOWN2.Integral()
	        UPFakes_mue_MU_RE = hmeFakes_MU_RE_UP2.Integral()
	        DNFakes_mue_MU_FR = hmeFakes_MU_FR_DOWN2.Integral()
	        UPFakes_mue_MU_FR = hmeFakes_MU_FR_UP2.Integral()
	
		DNScale_mue_EL_RE = DNFakes_mue_EL_RE/nomFakes_mue
		UPScale_mue_EL_RE = UPFakes_mue_EL_RE/nomFakes_mue
	        DNScale_mue_EL_FR = DNFakes_mue_EL_FR/nomFakes_mue
	        UPScale_mue_EL_FR = UPFakes_mue_EL_FR/nomFakes_mue
	        DNScale_mue_MU_RE = DNFakes_mue_MU_RE/nomFakes_mue
	        UPScale_mue_MU_RE = UPFakes_mue_MU_RE/nomFakes_mue
	        DNScale_mue_MU_FR = DNFakes_mue_MU_FR/nomFakes_mue
	        UPScale_mue_MU_FR = UPFakes_mue_MU_FR/nomFakes_mue
	
		DNScale_emu_EL_RE = DNFakes_emu_EL_RE/nomFakes_emu
	        UPScale_emu_EL_RE = UPFakes_emu_EL_RE/nomFakes_emu
	        DNScale_emu_EL_FR = DNFakes_emu_EL_FR/nomFakes_emu
	        UPScale_emu_EL_FR = UPFakes_emu_EL_FR/nomFakes_emu
        	DNScale_emu_MU_RE = DNFakes_emu_MU_RE/nomFakes_emu
	        UPScale_emu_MU_RE = UPFakes_emu_MU_RE/nomFakes_emu
	        DNScale_emu_MU_FR = DNFakes_emu_MU_FR/nomFakes_emu
	        UPScale_emu_MU_FR = UPFakes_emu_MU_FR/nomFakes_emu
	
		hemFakes_EL_RE_UP2.Scale(1./UPScale_emu_EL_RE)
	        hmeFakes_EL_RE_UP2.Scale(1./UPScale_mue_EL_RE)
	        hemFakes_EL_RE_DOWN2.Scale(1./DNScale_emu_EL_RE)
	        hmeFakes_EL_RE_DOWN2.Scale(1./DNScale_mue_EL_RE)
	        hemFakes_EL_FR_UP2.Scale(1./UPScale_emu_EL_FR)
	        hmeFakes_EL_FR_UP2.Scale(1./UPScale_mue_EL_FR)
	        hemFakes_EL_FR_DOWN2.Scale(1./DNScale_emu_EL_FR)
	        hmeFakes_EL_FR_DOWN2.Scale(1./DNScale_mue_EL_FR)
	        hemFakes_MU_RE_UP2.Scale(1./UPScale_emu_MU_RE)
	        hmeFakes_MU_RE_UP2.Scale(1./UPScale_mue_MU_RE)
	        hemFakes_MU_RE_DOWN2.Scale(1./DNScale_emu_MU_RE)
	        hmeFakes_MU_RE_DOWN2.Scale(1./DNScale_mue_MU_RE)
	        hemFakes_MU_FR_UP2.Scale(1./UPScale_emu_MU_FR)
	        hmeFakes_MU_FR_UP2.Scale(1./UPScale_mue_MU_FR)
	        hemFakes_MU_FR_DOWN2.Scale(1./DNScale_emu_MU_FR)
	        hmeFakes_MU_FR_DOWN2.Scale(1./DNScale_mue_MU_FR)
	
	
		### scaling for signal systmatics

		nomSig = hsg2.Integral()
		#yield_ATLAS_MU_SCALE_DOWN = hmeATLAS_MU_SCALE_DOWN2.Integral()
		#yield_ATLAS_MU_SCALE_UP = hmeATLAS_MU_SCALE_UP2.Integral()
		#yield_ATLAS_MET_RESOSOFT_DOWN = hmeATLAS_MET_RESOSOFT_DOWN2.Integral()
		#yield_ATLAS_MET_RESOSOFT_UP = hmeATLAS_MET_RESOSOFT_UP2.Integral()

		#DNScale_ATLAS_MU_SCALE = yield_ATLAS_MU_SCALE_DOWN/nomSig
		#UPScale_ATLAS_MU_SCALE = yield_ATLAS_MU_SCALE_UP/nomSig
		#DNScale_ATLAS_MET_RESOSOFT = yield_ATLAS_MET_RESOSOFT_DOWN/nomSig
		#UPScale_ATLAS_MET_RESOSOFT = yield_ATLAS_MET_RESOSOFT_UP/nomSig

		#hmeATLAS_MU_SCALE_DOWN2.Scale(1./DNScale_ATLAS_MU_SCALE)
		#hmeATLAS_MU_SCALE_UP2.Scale(1./UPScale_ATLAS_MU_SCALE)
		#hmeATLAS_MET_RESOSOFT_DOWN2.Scale(1./DNScale_ATLAS_MET_RESOSOFT)
		#hmeATLAS_MET_RESOSOFT_UP2.Scale(1./UPScale_ATLAS_MET_RESOSOFT)

	
	
		print " ***************************************8"
		print "emu_EL_RE = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_emu_EL_RE,DNScale_emu_EL_RE)
		print "emu_EL_FR = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_emu_EL_FR,DNScale_emu_EL_FR)
		print "emu_MU_RE = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_emu_MU_RE,DNScale_emu_MU_RE)
	        print "emu_MU_FR = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_emu_MU_FR,DNScale_emu_MU_FR)
		print "mue_EL_RE = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_mue_EL_RE,DNScale_mue_EL_RE)
	        print "mue_EL_FR = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_mue_EL_FR,DNScale_mue_EL_FR)
	        print "mue_MU_RE = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_mue_MU_RE,DNScale_mue_MU_RE)
	        print "mue_MU_FR = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_mue_MU_FR,DNScale_mue_MU_FR)
	
		#print "ATLAS_MU_SCALE = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_ATLAS_MU_SCALE,DNScale_ATLAS_MU_SCALE)
		#print "ATLAS_MET_RESOSOFT = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_ATLAS_MET_RESOSOFT,DNScale_ATLAS_MET_RESOSOFT)
	


		### Create baseline Bkg histo as average
		h_BaseBkg = hme2.Clone("Base_Bkg_l1pt%i%s"%(i,jet))
	        h_BaseBkg.Add(hem2)
	        h_BaseBkg.Scale(0.5)
	
	
		print "Bins : " ,ybinsnew[nthrow:]
		if strength>0 : print "**** Signal of %.2f was added ************" %strength
	
	
		hme2.Write()
		hem2.Write()
		h_BaseBkg.Write()
		hemFakes2.Write()
		hmeFakes2.Write()
		hemFakes_EL_RE_UP2.Write()
	        hmeFakes_EL_RE_UP2.Write()
		hemFakes_EL_RE_DOWN2.Write()
	        hmeFakes_EL_RE_DOWN2.Write()
		hemFakes_EL_FR_UP2.Write()
	        hmeFakes_EL_FR_UP2.Write()
		hemFakes_EL_FR_DOWN2.Write()
	        hmeFakes_EL_FR_DOWN2.Write()
		hemFakes_MU_RE_UP2.Write()
	        hmeFakes_MU_RE_UP2.Write()
		hemFakes_MU_RE_DOWN2.Write()
	        hmeFakes_MU_RE_DOWN2.Write()
		hemFakes_MU_FR_UP2.Write()
	        hmeFakes_MU_FR_UP2.Write()
		hemFakes_MU_FR_DOWN2.Write()
	        hmeFakes_MU_FR_DOWN2.Write()
		hsg2.Write()
		hwrsg2.Write()
		#hmeATLAS_MU_SCALE_DOWN2.Write()
		#hmeATLAS_MU_SCALE_UP2.Write()
		#hmeATLAS_MET_RESOSOFT_DOWN2.Write()
		#hmeATLAS_MET_RESOSOFT__UP2.Write()

	
	if strength>0 : print "**** Signal of %.2f was added ************" %strength
			
	#c3.Update()
	c3.SaveAs("data/Mcoll_SR%s.pdf"%jet)
		
	mem.append(frME)
	mem.append(frEM)
	#mem.append(frSig)
	#mem.append(c3)
	
#raw_input()

fw1.Close()
	
while len(mem)>0:
	item = mem.pop(0)
	del item
	
