#!/usr/bin/env python
#
# Prepare the inputs for HistFactory
#
# Carlos.Solans@cern.ch
# January 2014

import ROOT
import os
import sys
#import AtlasStyle
import array

"""
Prepare a dataset based on the inputs from Suneet (TH2D l1pt vs Mcoll).
"""

#AtlasStyle.SetAtlasStyle()

### INPUT DIR ##################

# DIR = "~/HistosApr30/"
# DIR = "/scratch/gerbaudo/hlfv_fit_tests/take1/R54_histos/"
# DIR = "/scratch/gerbaudo/hlfv_fit_tests/take1/FitModel/May_10_histos/"
DIR = "/scratch/gerbaudo/hlfv_fit_tests/take1/FitModel/Apr_26_histos/"
### SIGNAL STRENGTH ###########
strength = 0.0

### OUTPUT FILE ##############
fw1 = ROOT.TFile("data/simple.root","RECREATE")
mem = []
tln = ROOT.TLine()
l1b = array.array('d',(12,15,20,25,30,35,1000))
tla = ROOT.TLatex()


for jet in ('','_jets'):
#for jet in(''):

### FINAL BINNING ############
	### Mcoll Binning for jets sample
	ybinsnew = array.array('f', (0,60,80,100,120,130,140,150,160,180,200,230,260,300,350,400,450))
        ### Mcoll Binning for 0j sample
	if jet=='':
                ybinsnew = array.array('f',[0] + range(60, 250, 5) + [250,260,270,280,290,300,320,350,400,450])
        ### l1pt binning
	xbinsnew = array.array('f',(12,15,20,25,30,35,1000))

#############################
        data_variations = ['NOM']
        fake_variations = ['NOM',
                           'EL_RE_UP', 'EL_RE_DOWN', 'EL_FR_UP', 'EL_FR_DOWN',
                           'MU_RE_UP', 'MU_RE_DOWN', 'MU_FR_UP', 'MU_FR_DOWN']
        sign_variations = ['NOM']
	#### Get EM Files ####
        files_em = {}
        histos_em = {}
        for sample, variations in [('data', data_variations),
                                   ('fake', fake_variations),
                                   ('signaltaue', sign_variations)]:
                for variation in variations:
                        key = sample+'_'+variation+'_sr_emu_os'+jet
                        files_em[key] = ROOT.TFile(DIR+'/'+key+'.root')
                        histoname = 'h_mcoll_vs_pt1_'+sample+'_'+variation+'_sr_emu_os'+jet
                        clonename = ""
                        histos_em[key] = files_em[key].Get(histoname).Clone()

	frEM                 = ROOT.TFile(DIR+"data_NOM_sr_emu_os%s.root"%jet)
	frME_signaltaue      = ROOT.TFile(DIR+"signaltaue_NOM_sr_mue_os%s.root"%jet)
	frEM_fake            = ROOT.TFile(DIR+"fake_NOM_sr_emu_os%s.root"%jet)
	frEM_fake_EL_RE_UP   = ROOT.TFile(DIR+"fake_EL_RE_UP_sr_emu_os%s.root"%jet)
	frEM_fake_EL_RE_DOWN = ROOT.TFile(DIR+"fake_EL_RE_DOWN_sr_emu_os%s.root"%jet)
	frEM_fake_EL_FR_UP   = ROOT.TFile(DIR+"fake_EL_FR_UP_sr_emu_os%s.root"%jet)
	frEM_fake_EL_FR_DOWN = ROOT.TFile(DIR+"fake_EL_FR_DOWN_sr_emu_os%s.root"%jet)
	frEM_fake_MU_RE_UP   = ROOT.TFile(DIR+"fake_MU_RE_UP_sr_emu_os%s.root"%jet)
	frEM_fake_MU_RE_DOWN = ROOT.TFile(DIR+"fake_MU_RE_DOWN_sr_emu_os%s.root"%jet)
	frEM_fake_MU_FR_UP   = ROOT.TFile(DIR+"fake_MU_FR_UP_sr_emu_os%s.root"%jet)
	frEM_fake_MU_FR_DOWN = ROOT.TFile(DIR+"fake_MU_FR_DOWN_sr_emu_os%s.root"%jet)


	### Get ME files
	frME                 = ROOT.TFile(DIR+"data_NOM_sr_mue_os%s.root"%jet)
	frME_signaltaumu     = ROOT.TFile(DIR+"signaltaumu_NOM_sr_mue_os%s.root"%jet)
	frME_fake            = ROOT.TFile(DIR+"fake_NOM_sr_mue_os%s.root"%jet)
	frME_fake_EL_RE_UP   = ROOT.TFile(DIR+"fake_EL_RE_UP_sr_mue_os%s.root"%jet)
	frME_fake_EL_RE_DOWN = ROOT.TFile(DIR+"fake_EL_RE_DOWN_sr_mue_os%s.root"%jet)
	frME_fake_EL_FR_UP   = ROOT.TFile(DIR+"fake_EL_FR_UP_sr_mue_os%s.root"%jet)
	frME_fake_EL_FR_DOWN = ROOT.TFile(DIR+"fake_EL_FR_DOWN_sr_mue_os%s.root"%jet)
	frME_fake_MU_RE_UP   = ROOT.TFile(DIR+"fake_MU_RE_UP_sr_mue_os%s.root"%jet)
	frME_fake_MU_RE_DOWN = ROOT.TFile(DIR+"fake_MU_RE_DOWN_sr_mue_os%s.root"%jet)
	frME_fake_MU_FR_UP   = ROOT.TFile(DIR+"fake_MU_FR_UP_sr_mue_os%s.root"%jet)
	frME_fake_MU_FR_DOWN = ROOT.TFile(DIR+"fake_MU_FR_DOWN_sr_mue_os%s.root"%jet)


	### Get EM histograms

	h2emOrig                 = frEM.Get("h_mcoll_vs_pt1_data_NOM_sr_emu_os%s"%jet).Clone("EM%s"%jet)
	h2emOrig_fake            = frEM_fake.Get("h_mcoll_vs_pt1_fake_NOM_sr_emu_os%s"%jet).Clone("EM_fake%s"%jet)
	h2emOrig_fake_EL_RE_UP   = frEM_fake_EL_RE_UP.Get("h_mcoll_vs_pt1_fake_EL_RE_UP_sr_emu_os%s"%jet
                                                         ).Clone("EM_fake_EL_RE_UP%s"%jet)
	h2emOrig_fake_EL_RE_DOWN = frEM_fake_EL_RE_DOWN.Get("h_mcoll_vs_pt1_fake_EL_RE_DOWN_sr_emu_os%s"%jet
                                                            ).Clone("EM_fake_EL_RE_DOWN%s"%jet)
	h2emOrig_fake_EL_FR_UP   = frEM_fake_EL_FR_UP.Get("h_mcoll_vs_pt1_fake_EL_FR_UP_sr_emu_os%s"%jet
                                                          ).Clone("EM_fake_EL_FR_UP%s"%jet)
	h2emOrig_fake_EL_FR_DOWN = frEM_fake_EL_FR_DOWN.Get("h_mcoll_vs_pt1_fake_EL_FR_DOWN_sr_emu_os%s"%jet
                                                            ).Clone("EM_fake_EL_FR_DOWN%s"%jet)
	h2emOrig_fake_MU_RE_UP   = frEM_fake_MU_RE_UP.Get("h_mcoll_vs_pt1_fake_MU_RE_UP_sr_emu_os%s"%jet
                                                          ).Clone("EM_fake_MU_RE_UP%s"%jet)
	h2emOrig_fake_MU_RE_DOWN = frEM_fake_MU_RE_DOWN.Get("h_mcoll_vs_pt1_fake_MU_RE_DOWN_sr_emu_os%s"%jet).Clone("EM_fake_MU_RE_DOWN%s"%jet)
	h2emOrig_fake_MU_FR_UP   = frEM_fake_MU_FR_UP.Get("h_mcoll_vs_pt1_fake_MU_FR_UP_sr_emu_os%s"%jet
                                                          ).Clone("EM_fake_MU_FR_UP%s"%jet)
	h2emOrig_fake_MU_FR_DOWN = frEM_fake_MU_FR_DOWN.Get("h_mcoll_vs_pt1_fake_MU_FR_DOWN_sr_emu_os%s"%jet
                                                            ).Clone("EM_fake_MU_FR_DOWN%s"%jet)
	h2wrsgOrig               = frME_signaltaue.Get("h_mcoll_vs_pt1_signaltaue_NOM_sr_mue_os%s"%jet).Clone("ME_signaltaue%s"%jet)

	### Get ME histograms

	h2meOrig =                 frME.Get("h_mcoll_vs_pt1_data_NOM_sr_mue_os%s"%jet).Clone("ME%s"%jet)
	h2meOrig_fake =            frME_fake.Get("h_mcoll_vs_pt1_fake_NOM_sr_mue_os%s"%jet).Clone("ME_fake%s"%jet)
	h2meOrig_fake_EL_RE_UP =   frME_fake_EL_RE_UP.Get("h_mcoll_vs_pt1_fake_EL_RE_UP_sr_mue_os%s"%jet).Clone("ME_fake_EL_RE_UP%s"%jet)
	h2meOrig_fake_EL_RE_DOWN = frME_fake_EL_RE_DOWN.Get("h_mcoll_vs_pt1_fake_EL_RE_DOWN_sr_mue_os%s"%jet).Clone("ME_fake_EL_RE_DOWN%s"%jet)
	h2meOrig_fake_EL_FR_UP =   frME_fake_EL_FR_UP.Get("h_mcoll_vs_pt1_fake_EL_FR_UP_sr_mue_os%s"%jet).Clone("ME_fake_EL_FR_UP%s"%jet)
	h2meOrig_fake_EL_FR_DOWN = frME_fake_EL_FR_DOWN.Get("h_mcoll_vs_pt1_fake_EL_FR_DOWN_sr_mue_os%s"%jet).Clone("ME_fake_EL_FR_DOWN%s"%jet)
	h2meOrig_fake_MU_RE_UP =   frME_fake_MU_RE_UP.Get("h_mcoll_vs_pt1_fake_MU_RE_UP_sr_mue_os%s"%jet).Clone("ME_fake_MU_RE_UP%s"%jet)
	h2meOrig_fake_MU_RE_DOWN = frME_fake_MU_RE_DOWN.Get("h_mcoll_vs_pt1_fake_MU_RE_DOWN_sr_mue_os%s"%jet).Clone("ME_fake_MU_RE_DOWN%s"%jet)
	h2meOrig_fake_MU_FR_UP =   frME_fake_MU_FR_UP.Get("h_mcoll_vs_pt1_fake_MU_FR_UP_sr_mue_os%s"%jet).Clone("ME_fake_MU_FR_UP%s"%jet)
	h2meOrig_fake_MU_FR_DOWN = frME_fake_MU_FR_DOWN.Get("h_mcoll_vs_pt1_fake_MU_FR_DOWN_sr_mue_os%s"%jet).Clone("ME_fake_MU_FR_DOWN%s"%jet)
	h2sgOrig = frME_signaltaumu.Get("h_mcoll_vs_pt1_signaltaumu_NOM_sr_mue_os%s"%jet).Clone("ME_signaltaumu%s"%jet)

	## Rebin 2D histos ###

	print "Rebinning..."
	xaxis = h2meOrig.GetXaxis()
	yaxis = h2meOrig.GetYaxis()

	Sig_xaxis = h2sgOrig.GetXaxis()
	Sig_yaxis = h2sgOrig.GetYaxis()

        n_xbin = len(xbinsnew)-1
        n_ybin = len(ybinsnew)-1

        templ_h_name = 'h_SR_%s_Rebinned_mcollCorr_x_pt1_%s'
        title = "l_1 p^{T};Mcoll (GeV)"
	h2me                 = ROOT.TH2F(templ_h_name % ('ME', 'Data'            +jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2em                 = ROOT.TH2F(templ_h_name % ('EM', 'Data'            +jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2emFakes            = ROOT.TH2F(templ_h_name % ('EM', 'Fakes'           +jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2meFakes            = ROOT.TH2F(templ_h_name % ('ME', 'Fakes'           +jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2emFakes_EL_RE_UP   = ROOT.TH2F(templ_h_name % ('EM', 'Fakes_EL_RE_UP'  +jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2meFakes_EL_RE_UP   = ROOT.TH2F(templ_h_name % ('ME', 'Fakes_EL_RE_UP'  +jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2emFakes_EL_RE_DOWN = ROOT.TH2F(templ_h_name % ('EM', 'Fakes_EL_RE_DOWN'+jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2meFakes_EL_RE_DOWN = ROOT.TH2F(templ_h_name % ('ME', 'Fakes_EL_RE_DOWN'+jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2emFakes_EL_FR_UP   = ROOT.TH2F(templ_h_name % ('EM', 'Fakes_EL_FR_UP'  +jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2meFakes_EL_FR_UP   = ROOT.TH2F(templ_h_name % ('ME', 'Fakes_EL_FR_UP'  +jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2emFakes_EL_FR_DOWN = ROOT.TH2F(templ_h_name % ('EM', 'Fakes_EL_FR_DOWN'+jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2meFakes_EL_FR_DOWN = ROOT.TH2F(templ_h_name % ('ME', 'Fakes_EL_FR_DOWN'+jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2emFakes_MU_RE_UP   = ROOT.TH2F(templ_h_name % ('EM', 'Fakes_MU_RE_UP'  +jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2meFakes_MU_RE_UP   = ROOT.TH2F(templ_h_name % ('ME', 'Fakes_MU_RE_UP'  +jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2emFakes_MU_RE_DOWN = ROOT.TH2F(templ_h_name % ('EM', 'Fakes_MU_RE_DOWN'+jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2meFakes_MU_RE_DOWN = ROOT.TH2F(templ_h_name % ('ME', 'Fakes_MU_RE_DOWN'+jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2emFakes_MU_FR_UP   = ROOT.TH2F(templ_h_name % ('EM', 'Fakes_MU_FR_UP'  +jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2meFakes_MU_FR_UP   = ROOT.TH2F(templ_h_name % ('ME', 'Fakes_MU_FR_UP'  +jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2emFakes_MU_FR_DOWN = ROOT.TH2F(templ_h_name % ('EM', 'Fakes_MU_FR_DOWN'+jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2meFakes_MU_FR_DOWN = ROOT.TH2F(templ_h_name % ('ME', 'Fakes_MU_FR_DOWN'+jet), title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2sg      = ROOT.TH2F("h_SR_Sig_Rebinned_mcollCorr_x_pt1%s"%jet,      title,n_xbin,xbinsnew,n_ybin,ybinsnew)
	h2wrsg    = ROOT.TH2F("h_SR_WrongSig_Rebinned_mcollCorr_x_pt1%s"%jet, title,n_xbin,xbinsnew,n_ybin,ybinsnew)



        for h_orig, h_clone in [(h2meOrig                , h2me                ),
                                (h2emOrig                , h2em                ),
                                (h2emOrig_fake           , h2emFakes           ),
                                (h2meOrig_fake           , h2meFakes           ),
                                (h2emOrig_fake_EL_RE_UP  , h2emFakes_EL_RE_UP  ),
                                (h2meOrig_fake_EL_RE_UP  , h2meFakes_EL_RE_UP  ),
                                (h2emOrig_fake_EL_RE_DOWN, h2emFakes_EL_RE_DOWN),
                                (h2meOrig_fake_EL_RE_DOWN, h2meFakes_EL_RE_DOWN),
                                (h2emOrig_fake_EL_FR_UP  , h2emFakes_EL_FR_UP  ),
                                (h2meOrig_fake_EL_FR_UP  , h2meFakes_EL_FR_UP  ),
                                (h2emOrig_fake_EL_FR_DOWN, h2emFakes_EL_FR_DOWN),
                                (h2meOrig_fake_EL_FR_DOWN, h2meFakes_EL_FR_DOWN),
                                (h2emOrig_fake_MU_RE_UP  , h2emFakes_MU_RE_UP  ),
                                (h2meOrig_fake_MU_RE_UP  , h2meFakes_MU_RE_UP  ),
                                (h2emOrig_fake_MU_RE_DOWN, h2emFakes_MU_RE_DOWN),
                                (h2meOrig_fake_MU_RE_DOWN, h2meFakes_MU_RE_DOWN),
                                (h2emOrig_fake_MU_FR_UP  , h2emFakes_MU_FR_UP  ),
                                (h2meOrig_fake_MU_FR_UP  , h2meFakes_MU_FR_UP  ),
                                (h2emOrig_fake_MU_FR_DOWN, h2emFakes_MU_FR_DOWN),
                                (h2meOrig_fake_MU_FR_DOWN, h2meFakes_MU_FR_DOWN),
                                (h2sgOrig                , h2sg                ), # why was this outside of the loop?
                                (h2wrsgOrig              , h2wrsg              ),
                                ]:
                xaxis = h_orig.GetXaxis()
                yaxis = h_orig.GetYaxis()
                for x in range(xaxis.GetNbins()):
                        for y in range(yaxis.GetNbins()):
                                i=x+1
                                j=y+1
                                ix = xaxis.GetBinCenter(i)
                                jy = yaxis.GetBinCenter(j)
                                h_clone.Fill(ix, jy, h_orig.GetBinContent(i, j))


	## Rebin uniformly to indices
        xaxis = h2me.GetXaxis()
        yaxis = h2me.GetYaxis()
	nbinsx = xaxis.GetNbins()
	nbinsy = yaxis.GetNbins()
	bpme = array.array('f', [xaxis.GetBinLowEdge(j+1) for j in range(nbinsx+1)])
	bmme = array.array('f', [yaxis.GetBinLowEdge(k+1) for k in range(nbinsy+1)])
	n_m_bins = len(bmme)-1
	c3 = ROOT.TCanvas("c3%s"%jet,"Mcol%s"%jet,800,800)
	c3.Divide(3,len(l1b)-1)
	for i in range(len(l1b)-1):
		hme1 = ROOT.TH1F("Mcoll_data_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
		hem1 = ROOT.TH1F("Mcoll_data_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
		hemFakes1 = ROOT.TH1F("Mcoll_Fakes_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
		hmeFakes1 = ROOT.TH1F("Mcoll_Fakes_M_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
		hemFakes_EL_RE_UP1   = ROOT.TH1F("Mcoll_Fakes_EL_RE_UP_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
	        hmeFakes_EL_RE_UP1   = ROOT.TH1F("Mcoll_Fakes_EL_RE_UP_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
		hemFakes_EL_RE_DOWN1 = ROOT.TH1F("Mcoll_Fakes_EL_RE_DOWN_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
	        hmeFakes_EL_RE_DOWN1 = ROOT.TH1F("Mcoll_Fakes_EL_RE_DOWN_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
		hemFakes_EL_FR_UP1   = ROOT.TH1F("Mcoll_Fakes_EL_FR_UP_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
	        hmeFakes_EL_FR_UP1   = ROOT.TH1F("Mcoll_Fakes_EL_FR_UP_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
		hemFakes_EL_FR_DOWN1 = ROOT.TH1F("Mcoll_Fakes_EL_FR_DOWN_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
	        hmeFakes_EL_FR_DOWN1 = ROOT.TH1F("Mcoll_Fakes_EL_FR_DOWN_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
		hemFakes_MU_RE_UP1   = ROOT.TH1F("Mcoll_Fakes_MU_RE_UP_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
	        hmeFakes_MU_RE_UP1   = ROOT.TH1F("Mcoll_Fakes_MU_RE_UP_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
		hemFakes_MU_RE_DOWN1 = ROOT.TH1F("Mcoll_Fakes_MU_RE_DOWN_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
	        hmeFakes_MU_RE_DOWN1 = ROOT.TH1F("Mcoll_Fakes_MU_RE_DOWN_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
		hemFakes_MU_FR_UP1   = ROOT.TH1F("Mcoll_Fakes_MU_FR_UP_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
	        hmeFakes_MU_FR_UP1   = ROOT.TH1F("Mcoll_Fakes_MU_FR_UP_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
		hemFakes_MU_FR_DOWN1 = ROOT.TH1F("Mcoll_Fakes_MU_FR_DOWN_EM_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)
	        hmeFakes_MU_FR_DOWN1 = ROOT.TH1F("Mcoll_Fakes_MU_FR_DOWN_ME_l1pt%i%s"%(i,jet),  ";Mcoll (GeV)",n_m_bins,bmme)

		hsg1 = ROOT.TH1F("Mcoll_signal_ME_l1pt%i%s"%(i,jet),";Mcoll (GeV)",n_m_bins,bmme)
		hwrsg1 = ROOT.TH1F("Mcoll_wrong_signal_ME_l1pt%i%s"%(i,jet),";Mcoll (GeV)",n_m_bins,bmme)


		mem.append(hme1)
		mem.append(hem1)
		mem.append(hsg1)
		mem.append(hwrsg1)
		for pt in bpme:
			htme                  = ROOT.TH1F("htme","htme",n_m_bins,bmme)
			htem                  = ROOT.TH1F("htem","htem",n_m_bins,bmme)
			htsg                  = ROOT.TH1F("htsg","htsg",n_m_bins,bmme)
			htwrsg                = ROOT.TH1F("htwrsg","htwrsg",n_m_bins,bmme)
			htemFakes             = ROOT.TH1F("htemFakes","htemFakes",n_m_bins,bmme)
			htmeFakes             = ROOT.TH1F("htmeFakes","htmeFakes",n_m_bins,bmme)
			htemFakes_EL_RE_UP    = ROOT.TH1F("htemFakes_EL_RE_UP","htemFakes_EL_RE_UP",n_m_bins,bmme)
	                htmeFakes_EL_RE_UP    = ROOT.TH1F("htmeFakes_EL_RE_UP","htmeFakes_EL_RE_UP",n_m_bins,bmme)
			htemFakes_EL_RE_DOWN  = ROOT.TH1F("htemFakes_EL_RE_DOWN","htemFakes_EL_RE_DOWN",n_m_bins,bmme)
	                htmeFakes_EL_RE_DOWN  = ROOT.TH1F("htmeFakes_EL_RE_DOWN","htmeFakes_EL_RE_DOWN",n_m_bins,bmme)
			htemFakes_EL_FR_UP    = ROOT.TH1F("htemFakes_EL_FR_UP","htemFakes_EL_FR_UP",n_m_bins,bmme)
	                htmeFakes_EL_FR_UP    = ROOT.TH1F("htmeFakes_EL_FR_UP","htmeFakes_EL_FR_UP",n_m_bins,bmme)
			htemFakes_EL_FR_DOWN  = ROOT.TH1F("htemFakes_EL_FR_DOWN","htemFakes_EL_FR_DOWN",n_m_bins,bmme)
	                htmeFakes_EL_FR_DOWN  = ROOT.TH1F("htmeFakes_EL_FR_DOWN","htmeFakes_EL_FR_DOWN",n_m_bins,bmme)
			htemFakes_MU_RE_UP    = ROOT.TH1F("htemFakes_MU_RE_UP","htemFakes_MU_RE_UP",n_m_bins,bmme)
	                htmeFakes_MU_RE_UP    = ROOT.TH1F("htmeFakes_MU_RE_UP","htmeFakes_MU_RE_UP",n_m_bins,bmme)
			htemFakes_MU_RE_DOWN  = ROOT.TH1F("htemFakes_MU_RE_DOWN","htemFakes_MU_RE_DOWN",n_m_bins,bmme)
	                htmeFakes_MU_RE_DOWN  = ROOT.TH1F("htmeFakes_MU_RE_DOWN","htmeFakes_MU_RE_DOWN",n_m_bins,bmme)
			htemFakes_MU_FR_UP    = ROOT.TH1F("htemFakes_MU_FR_UP","htemFakes_MU_FR_UP",n_m_bins,bmme)
	                htmeFakes_MU_FR_UP    = ROOT.TH1F("htmeFakes_MU_FR_UP","htmeFakes_MU_FR_UP",n_m_bins,bmme)
			htemFakes_MU_FR_DOWN  = ROOT.TH1F("htemFakes_MU_FR_DOWN","htemFakes_MU_FR_DOWN",n_m_bins,bmme)
	                htmeFakes_MU_FR_DOWN  = ROOT.TH1F("htmeFakes_MU_FR_DOWN","htmeFakes_MU_FR_DOWN",n_m_bins,bmme)

			if pt<l1b[i+1] and pt>=l1b[i]:
				if False: print "add pt: %.2f" %pt
				for mass in bmme:
					if False: print "mass:",mass,"pt:",pt,"pt_bin:",l1b[i]

                                        for h_dest, h_orig in [(htme,                h2me),
                                                               (htem,                h2em),
                                                               (htsg,                h2sg),
                                                               (htwrsg,              h2wrsg),
                                                               (htemFakes,           h2emFakes),
                                                               (htmeFakes,           h2meFakes),
                                                               (htemFakes_EL_RE_UP,  h2emFakes_EL_RE_UP),
                                                               (htmeFakes_EL_RE_UP,  h2meFakes_EL_RE_UP),
                                                               (htemFakes_EL_RE_DOWN,h2emFakes_EL_RE_DOWN),
                                                               (htmeFakes_EL_RE_DOWN,h2meFakes_EL_RE_DOWN),
                                                               (htemFakes_EL_FR_UP,  h2emFakes_EL_FR_UP),
                                                               (htmeFakes_EL_FR_UP,  h2meFakes_EL_FR_UP),
                                                               (htemFakes_EL_FR_DOWN,h2emFakes_EL_FR_DOWN),
                                                               (htmeFakes_EL_FR_DOWN,h2meFakes_EL_FR_DOWN),
                                                               (htemFakes_MU_RE_UP,  h2emFakes_MU_RE_UP),
                                                               (htmeFakes_MU_RE_UP,  h2meFakes_MU_RE_UP),
                                                               (htemFakes_MU_RE_DOWN,h2emFakes_MU_RE_DOWN),
                                                               (htmeFakes_MU_RE_DOWN,h2meFakes_MU_RE_DOWN),
                                                               (htemFakes_MU_FR_UP,  h2emFakes_MU_FR_UP),
                                                               (htmeFakes_MU_FR_UP,  h2meFakes_MU_FR_UP),
                                                               (htemFakes_MU_FR_DOWN,h2emFakes_MU_FR_DOWN),
                                                               (htmeFakes_MU_FR_DOWN,h2meFakes_MU_FR_DOWN),
                                                               ]:
                                                dest_bin = h_dest.FindBin(mass)
                                                orig_bin = h_orig.FindBin(pt, mass)
                                                h_dest.SetBinContent(dest_bin, h_orig.GetBinContent(orig_bin))
                                                h_dest.SetBinError  (dest_bin, h_orig.GetBinError  (orig_bin))

				hme1.Add(htme)
				hem1.Add(htem)
				hsg1.Add(htsg)
				hwrsg1.Add(htwrsg)
				hemFakes1.Add(htemFakes)
				hmeFakes1.Add(htmeFakes)
				hemFakes_EL_RE_UP1.Add(htemFakes_EL_RE_UP)
	                        hmeFakes_EL_RE_UP1.Add(htmeFakes_EL_RE_UP)
				hemFakes_EL_RE_DOWN1.Add(htemFakes_EL_RE_DOWN)
	                        hmeFakes_EL_RE_DOWN1.Add(htmeFakes_EL_RE_DOWN)
				hemFakes_EL_FR_UP1.Add(htemFakes_EL_FR_UP)
	                        hmeFakes_EL_FR_UP1.Add(htmeFakes_EL_FR_UP)
				hemFakes_EL_FR_DOWN1.Add(htemFakes_EL_FR_DOWN)
	                        hmeFakes_EL_FR_DOWN1.Add(htmeFakes_EL_FR_DOWN)
				hemFakes_MU_RE_UP1.Add(htemFakes_MU_RE_UP)
	                        hmeFakes_MU_RE_UP1.Add(htmeFakes_MU_RE_UP)
				hemFakes_MU_RE_DOWN1.Add(htemFakes_MU_RE_DOWN)
	                        hmeFakes_MU_RE_DOWN1.Add(htmeFakes_MU_RE_DOWN)
				hemFakes_MU_FR_UP1.Add(htemFakes_MU_FR_UP)
	                        hmeFakes_MU_FR_UP1.Add(htmeFakes_MU_FR_UP)
				hemFakes_MU_FR_DOWN1.Add(htemFakes_MU_FR_DOWN)
	                        hmeFakes_MU_FR_DOWN1.Add(htmeFakes_MU_FR_DOWN)

			htme.Clear()
			htem.Clear()
			htsg.Clear()
			htwrsg.Clear()
			htemFakes.Clear()
			htmeFakes.Clear()
			htemFakes_EL_RE_UP.Clear()
	                htmeFakes_EL_RE_UP.Clear()
			htemFakes_EL_RE_DOWN.Clear()
	                htmeFakes_EL_RE_DOWN.Clear()
			htemFakes_EL_FR_UP.Clear()
	                htmeFakes_EL_FR_UP.Clear()
			htemFakes_EL_FR_DOWN.Clear()
	                htmeFakes_EL_FR_DOWN.Clear()
			htemFakes_MU_RE_UP.Clear()
	                htmeFakes_MU_RE_UP.Clear()
			htemFakes_MU_RE_DOWN.Clear()
	                htmeFakes_MU_RE_DOWN.Clear()
			htemFakes_MU_FR_UP.Clear()
	                htmeFakes_MU_FR_UP.Clear()
			htemFakes_MU_FR_DOWN.Clear()
	                htmeFakes_MU_FR_DOWN.Clear()


		#### ADD SIGNAL TO SUM MC ###
		hme1.Add(hsg1,strength)
		hem1.Add(hwrsg1,strength)
		####

		c3.cd(3*i+1)
		hme1.Draw()
		#tla.DrawLatexNDC(0.3,0.8,"Mcoll data ME %s l1pt %i-%i"%(jet,l1b[i],l1b[i+1]))
		c3.cd(3*i+2)
		hem1.Draw()
		#tla.DrawLatexNDC(0.3,0.8,"Mcoll data EM %s l1pt %i-%i"%(jet,l1b[i],l1b[i+1]))
		c3.cd(3*i+3)
		hsg1.Draw()
		#tla.DrawLatexNDC(0.3,0.8,"Mcoll signal ME %s l1pt %i-%i"%(jet,l1b[i],l1b[i+1]))
		fw1.cd()
		hme1.Write()
		hem1.Write()
		hsg1.Write()
		hwrsg1.Write()
		if False: print "Rebin histos"
		##throw away first bins
		nthrow = 0
                title = ';Mcoll (index)'
                basename = ''
                n_m_bins_pruned = len(bmme)-nthrow
                pre_name = 'Mcoll_'
                suf_name = "l1pt%i%s_rebin"%(i,jet)
		hme2                 = ROOT.TH1F(pre_name+'_data_ME_'        +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
		hem2                 = ROOT.TH1F(pre_name+'_data_EM_'        +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
		hsg2                 = ROOT.TH1F(pre_name+'_signal_ME_'      +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
		hwrsg2               = ROOT.TH1F(pre_name+'_wrong_signal_ME_'+suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
                pre_name = 'Mcoll_Fakes'
		hemFakes2            = ROOT.TH1F(pre_name+'_Fakes_EM_'       +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
		hmeFakes2            = ROOT.TH1F(pre_name+'_Fakes_ME_'       +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
		hemFakes_EL_RE_UP2   = ROOT.TH1F(pre_name+'_EL_RE_UP_EM_'    +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
	        hmeFakes_EL_RE_UP2   = ROOT.TH1F(pre_name+'_EL_RE_UP_ME_'    +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
		hemFakes_EL_RE_DOWN2 = ROOT.TH1F(pre_name+'_EL_RE_DOWN_EM_'  +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
	        hmeFakes_EL_RE_DOWN2 = ROOT.TH1F(pre_name+'_EL_RE_DOWN_ME_'  +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
		hemFakes_EL_FR_UP2   = ROOT.TH1F(pre_name+'_EL_FR_UP_EM_'    +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
	        hmeFakes_EL_FR_UP2   = ROOT.TH1F(pre_name+'_EL_FR_UP_ME_'    +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
		hemFakes_EL_FR_DOWN2 = ROOT.TH1F(pre_name+'_EL_FR_DOWN_EM_'  +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
	        hmeFakes_EL_FR_DOWN2 = ROOT.TH1F(pre_name+'_EL_FR_DOWN_ME_'  +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
		hemFakes_MU_RE_UP2   = ROOT.TH1F(pre_name+'_MU_RE_UP_EM_'    +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
	        hmeFakes_MU_RE_UP2   = ROOT.TH1F(pre_name+'_MU_RE_UP_ME_'    +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
		hemFakes_MU_RE_DOWN2 = ROOT.TH1F(pre_name+'_MU_RE_DOWN_EM_'  +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
	        hmeFakes_MU_RE_DOWN2 = ROOT.TH1F(pre_name+'_MU_RE_DOWN_ME_'  +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
		hemFakes_MU_FR_UP2   = ROOT.TH1F(pre_name+'_MU_FR_UP_EM_'    +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
	        hmeFakes_MU_FR_UP2   = ROOT.TH1F(pre_name+'_MU_FR_UP_ME_'    +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
		hemFakes_MU_FR_DOWN2 = ROOT.TH1F(pre_name+'_MU_FR_DOWN_EM_'  +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)
	        hmeFakes_MU_FR_DOWN2 = ROOT.TH1F(pre_name+'_MU_FR_DOWN_ME_'  +suf_name, title,n_m_bins_pruned,0,n_m_bins_pruned)


		mem.append(hme2)
		mem.append(hem2)
		mem.append(hemFakes2)
		mem.append(hmeFakes2)
		mem.append(hsg2)
		mem.append(hwrsg2)

		for b in range(n_m_bins_pruned):
                        for h_orig, h_dest in [(hme1,                 hme2),
                                               (hem1,                 hem2),
                                               (hsg1,                 hsg2),
                                               (hwrsg1,               hwrsg2),
                                               (hemFakes1,            hemFakes2),
                                               (hmeFakes1,            hmeFakes2),
                                               (hemFakes_EL_RE_UP1,   hemFakes_EL_RE_UP2),
                                               (hmeFakes_EL_RE_UP1,   hmeFakes_EL_RE_UP2),
                                               (hemFakes_EL_RE_DOWN1, hemFakes_EL_RE_DOWN2),
                                               (hmeFakes_EL_RE_DOWN1, hmeFakes_EL_RE_DOWN2),
                                               (hemFakes_EL_FR_UP1,   hemFakes_EL_FR_UP2),
                                               (hmeFakes_EL_FR_UP1,   hmeFakes_EL_FR_UP2),
                                               (hemFakes_EL_FR_DOWN1, hemFakes_EL_FR_DOWN2),
                                               (hmeFakes_EL_FR_DOWN1, hmeFakes_EL_FR_DOWN2),
                                               (hemFakes_MU_RE_UP1,   hemFakes_MU_RE_UP2),
                                               (hmeFakes_MU_RE_UP1,   hmeFakes_MU_RE_UP2),
                                               (hemFakes_MU_RE_DOWN1, hemFakes_MU_RE_DOWN2),
                                               (hmeFakes_MU_RE_DOWN1, hmeFakes_MU_RE_DOWN2),
                                               (hemFakes_MU_FR_UP1,   hemFakes_MU_FR_UP2),
                                               (hmeFakes_MU_FR_UP1,   hmeFakes_MU_FR_UP2),
                                               (hemFakes_MU_FR_DOWN1, hemFakes_MU_FR_DOWN2),
                                               (hmeFakes_MU_FR_DOWN1, hmeFakes_MU_FR_DOWN2),
                                               ]:
                                bin_orig = b+1+nthrow
                                bin_dest = b+1
                                if h_orig.GetBinContent(bin_orig)>0:
                                        h_dest.SetBinContent(bin_dest, h_orig.GetBinContent(bin_orig))
                                        h_dest.SetBinError  (bin_dest, h_orig.GetBinError  (bin_orig))
                                else:
                                        h_dest.SetBinContent(bin_dest, 0.001)
                                        h_dest.SetBinError  (bin_dest, 0.00001)
			if hwrsg2.GetBinContent(b+1)<0: # why a different treatment for hwrsg2 ?
				print "NEGATIVE VALUES in wrong signal sample!"

		### Get scaling for fake systematics
		nomFakes_emu = hemFakes2.Integral()
                for h in [hemFakes_EL_RE_DOWN2, hemFakes_EL_RE_UP2,
                          hemFakes_EL_FR_DOWN2, hemFakes_EL_FR_UP2,
                          hemFakes_MU_RE_DOWN2, hemFakes_MU_RE_UP2,
                          hemFakes_MU_FR_DOWN2, hemFakes_MU_FR_UP2]:
                        h.Scale(1.0/(h.Integral()/nomFakes_emu))
		nomFakes_mue = hmeFakes2.Integral()
                for h in [hmeFakes_EL_RE_DOWN2, hmeFakes_EL_RE_UP2,
                          hmeFakes_EL_FR_DOWN2, hmeFakes_EL_FR_UP2,
                          hmeFakes_MU_RE_DOWN2, hmeFakes_MU_RE_UP2,
                          hmeFakes_MU_FR_DOWN2, hmeFakes_MU_FR_UP2]:
                        h.Scale(1.0/(h.Integral()/nomFakes_mue))
		# print " ***************************************8"
		# print "emu_EL_RE = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_emu_EL_RE,DNScale_emu_EL_RE)
		# print "emu_EL_FR = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_emu_EL_FR,DNScale_emu_EL_FR)
		# print "emu_MU_RE = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_emu_MU_RE,DNScale_emu_MU_RE)
	        # print "emu_MU_FR = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_emu_MU_FR,DNScale_emu_MU_FR)
		# print "mue_EL_RE = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_mue_EL_RE,DNScale_mue_EL_RE)
	        # print "mue_EL_FR = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_mue_EL_FR,DNScale_mue_EL_FR)
	        # print "mue_MU_RE = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_mue_MU_RE,DNScale_mue_MU_RE)
	        # print "mue_MU_FR = {'%s':{'l1pt%i':{'UPvalue':%f,'DNvalue':%f}," %(jet,i,UPScale_mue_MU_FR,DNScale_mue_MU_FR)

		### scaling for signal systmatics
		nomSig = hsg2.Integral()
		### Create baseline Bkg histo as average
		h_BaseBkg = hme2.Clone("Base_Bkg_l1pt%i%s"%(i,jet))
	        h_BaseBkg.Add(hem2)
	        h_BaseBkg.Scale(0.5)
		print "Bins : " ,ybinsnew[nthrow:]
		if strength>0 : print "**** Signal of %.2f was added ************" %strength

                for h in [h_BaseBkg,
                          hsg2, hwrsg2,
                          hme2, hem2,
                          hemFakes2,            hmeFakes2,
                          hemFakes_EL_RE_UP2,   hmeFakes_EL_RE_UP2,
                          hemFakes_EL_RE_DOWN2, hmeFakes_EL_RE_DOWN2,
                          hemFakes_EL_FR_UP2,   hmeFakes_EL_FR_UP2,
                          hemFakes_EL_FR_DOWN2, hmeFakes_EL_FR_DOWN2,
                          hemFakes_MU_RE_UP2,   hmeFakes_MU_RE_UP2,
                          hemFakes_MU_RE_DOWN2, hmeFakes_MU_RE_DOWN2,
                          hemFakes_MU_FR_UP2,   hmeFakes_MU_FR_UP2,
                          hemFakes_MU_FR_DOWN2, hmeFakes_MU_FR_DOWN2]:
                        h.Write()


	if strength>0 : print "**** Signal of %.2f was added ************" %strength

	#c3.Update()
	c3.SaveAs("data/Mcoll_SR%s.pdf"%jet)

	mem.append(frME)
	mem.append(frEM)
	#mem.append(frSig)
	#mem.append(c3)

#raw_input()

fw1.Close()

while len(mem)>0:
	item = mem.pop(0)
	del item

